In [1]:
import pandas as pd
import numpy as np
import pathlib as pth

from scripts.add_features import add_calendar_features_lgb, add_weather_features_lgb, get_lgb_features_cols

In [2]:
def transform_dataframe(path: pth.Path, feature_cols: list[str]) -> pd.DataFrame:
    df = pd.read_csv(path, index_col=[0], parse_dates=["date"])

    df_features = add_calendar_features_lgb(add_weather_features_lgb(df))

    
    df_features_only = df_features[feature_cols]

    if "count" in df.columns:
        df_features_only["count"] = df["count"]

    return df_features_only

In [3]:
FEATURE_COLS = get_lgb_features_cols()

In [4]:
df_train = transform_dataframe(pth.Path(f"data-00-raw/bike_train.csv"), FEATURE_COLS)

df_train

     temp  atemp    hum   wind  ... cos_doy_2     sin_doy_3  cos_doy_3  count
1     9.1   13.2  79.78  10.43  ...  0.999407  5.161967e-02   0.998667    982
2     9.9   12.7  68.91  16.16  ...  0.997630  1.031017e-01   0.994671    797
3     3.1    4.5  43.29  16.14  ...  0.994671  1.543088e-01   0.988023   1351
4     3.2    5.6  58.45  10.42  ...  0.990532  2.051045e-01   0.978740   1559
5     4.3    6.5  43.26  12.15  ...  0.985220  2.553533e-01   0.966848   1597
..    ...    ...    ...    ...  ...       ...           ...        ...    ...
361   8.3   11.4  75.49  12.25  ...  0.990532 -2.051045e-01   0.978740   1161
362   7.3    9.0  49.89  19.11  ...  0.994671 -1.543088e-01   0.988023   2301
363   5.2    8.2  56.84   7.76  ...  0.997630 -1.031017e-01   0.994671   2421
364   7.8   10.9  63.03   8.73  ...  0.999407 -5.161967e-02   0.998667   2995
365  11.8   15.7  60.97  14.31  ...  1.000000 -7.347881e-16   1.000000   2485

[365 rows x 24 columns]

In [5]:
df_test = transform_dataframe(pth.Path(f"data-00-raw/bike_test.csv"), FEATURE_COLS)

df_test

     temp  atemp    hum  ...  cos_doy_2     sin_doy_3  cos_doy_3
1    10.2   13.8  68.56  ...   0.999407  5.161967e-02   0.998667
2     6.2    7.6  37.75  ...   0.997630  1.031017e-01   0.994671
3     1.1    1.3  43.68  ...   0.994671  1.543088e-01   0.988023
4    -0.6    1.0  41.04  ...   0.990532  2.051045e-01   0.978740
5     5.9    8.9  51.89  ...   0.985220  2.553533e-01   0.966848
..    ...    ...    ...  ...        ...           ...        ...
361   5.0    6.0  81.51  ...   0.990532 -2.051045e-01   0.978740
362   5.4    6.3  64.64  ...   0.994671 -1.543088e-01   0.988023
363   5.4    7.8  58.41  ...   0.997630 -1.031017e-01   0.994671
364   5.4    7.1  74.54  ...   0.999407 -5.161967e-02   0.998667
365   5.5    6.6  47.85  ...   1.000000 -7.347881e-16   1.000000

[365 rows x 23 columns]

In [6]:
df_train.to_csv(f"data-01-processed/lgb_regression_train.csv")

df_test.to_csv(f"data-01-processed/lgb_regression_test.csv")