### Nazwa na kaggle:
`Karol Chądzyński`

### Załączone Submissions (2):
1. `2026-06-11___22:32:55___95.csv` 
    - Submission którego nie jestem w stanie z jakiegoś powodu oddtworzyć w pythonie, mimo zapisanych parametrów oraz tych samych features (gdzie jednak w ewentualnej ich zmianie domniemuje winy), jako że nie mam na nie "dowodów", załączam poniżej te na które mam dowód.
2. `2026-06-14___22:27:04___125.csv`
    - Submission które sprawuje się nieco gorzej, ale mam na nie dowód w pełni w pythonie.

### Dodatki:
- Plik był robiony w pythonie i tłumaczony z niego na R, mogą być między wynikami pewne różnice.
- Dlatego załączam poniżej link do repozytorium github, na którym znajduje się pełny kod pythona i wszystkie spushowane zmiany.
- Zgodnie z treścią projketu, nie załączam przeszukiwania przestrzeni hiperparametrów (były robione optuną w pythonie, znajdują się na repo), nie mniej submision (`2026-06-14___22:27:04___125.csv`) było z pozostawionych parametrów `best_params`.

### `best_params`

`best_params = {'max_depth': 6, 'n_estimators': 420, 'learning_rate': 0.03, 'subsample': 0.608, 'colsample_bytree': 0.546, 'colsample_bylevel': 0.76, 'colsample_bynode': 0.587, 'min_child_weight': 5, 'gamma': 0.001, 'max_delta_step': 1.3, 'reg_alpha': 0.14, 'reg_lambda': 3.878, 'tree_method': 'hist', 'random_state': 42}`

### Link do repozytorium:
- `https://github.com/Karolcha100/SAD_2026_proj2_in_python`

In [1]:
import pandas as pd
import numpy as np

RANDOM_STATE = 42

In [2]:
df_train = pd.read_csv(f"data-00-raw/bike_train.csv", index_col=[0], parse_dates=["date"])

df_train

          date  wcond  temp  atemp    hum   wind  count
1   2022-01-01      2   9.1   13.2  79.78  10.43    982
2   2022-01-02      2   9.9   12.7  68.91  16.16    797
3   2022-01-03      1   3.1    4.5  43.29  16.14   1351
4   2022-01-04      1   3.2    5.6  58.45  10.42   1559
5   2022-01-05      1   4.3    6.5  43.26  12.15   1597
..         ...    ...   ...    ...    ...    ...    ...
361 2022-12-27      2   8.3   11.4  75.49  12.25   1161
362 2022-12-28      1   7.3    9.0  49.89  19.11   2301
363 2022-12-29      1   5.2    8.2  56.84   7.76   2421
364 2022-12-30      1   7.8   10.9  63.03   8.73   2995
365 2022-12-31      1  11.8   15.7  60.97  14.31   2485

[365 rows x 7 columns]

In [3]:
df_test = pd.read_csv(f"data-00-raw/bike_test.csv", index_col=[0], parse_dates=["date"])

df_test

          date  wcond  temp  atemp    hum   wind
1   2023-01-01      1  10.2   13.8  68.56  12.49
2   2023-01-02      1   6.2    7.6  37.75  21.43
3   2023-01-03      1   1.1    1.3  43.68  23.77
4   2023-01-04      2  -0.6    1.0  41.04  12.01
5   2023-01-05      1   5.9    8.9  51.89   8.45
..         ...    ...   ...    ...    ...    ...
361 2023-12-27      3   5.0    6.0  81.51  20.58
362 2023-12-28      2   5.4    6.3  64.64  22.76
363 2023-12-29      2   5.4    7.8  58.41  10.11
364 2023-12-30      2   5.4    7.1  74.54   8.08
365 2023-12-31      1   5.5    6.6  47.85  22.80

[365 rows x 6 columns]

# Features Engineering

In [4]:
import holidays

In [5]:
def add_fourier_features(df: pd.DataFrame, n_harmonics: int = 3) -> pd.DataFrame:
    """Add Fourier seasonality terms for annual cycle.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame with ``dayofyear`` column.
    n_harmonics : int
        Number of harmonics to generate.

    Returns
    -------
    pd.DataFrame
        DataFrame with added sin/cos Fourier columns.
    """
    for k in range(1, n_harmonics + 1):
        df[f"sind{k}"] = np.sin(2 * np.pi * k * df["doy"] / 365)
        df[f"cosd{k}"] = np.cos(2 * np.pi * k * df["doy"] / 365)
    return df

def build_features(
        df: pd.DataFrame,
    ) -> pd.DataFrame:
    """Build full feature matrix from raw bike sharing data.

    Parameters
    ----------
    df : pd.DataFrame
        Raw DataFrame with columns: date, temp, atemp, hum, wind, wcond.

    Returns
    -------
    pd.DataFrame
        DataFrame with engineered features, without target column.
    """
    df = df.copy()
    df["date"] = pd.to_datetime(df["date"])

    df["month"] = df["date"].dt.month
    df["dow"] = df["date"].dt.dayofweek
    df["doy"] = df["date"].dt.dayofyear
    df["quart"] = df["date"].dt.quarter
    df["week"] = (df["dow"] >= 5).astype(int)
    df["doy_norm"] = df["doy"] / 365

    df["t"] = (df["date"] - pd.Timestamp("2022-01-01")).dt.days

    df["temp2"] = df["temp"] ** 2
    df["temp3"] = df["temp"] ** 3
    df["hum2"] = df["hum"] ** 2
    df["wind2"] = df["wind"] ** 2
    df["temp-atemp"] = df["temp"] - df["atemp"]

    df["tempxhum"] = df["temp"] * df["hum"]
    df["tempxwind"] = df["temp"] * df["wind"]
    df["atempxhum"] = df["atemp"] * df["hum"]
    df["humxwind"] = df["hum"] * df["wind"]
    df["wcondxtemp"] = df["wcond"] * df["temp"]

    # New Features
    ##############
    # df["is_summer"] = df["month"].isin([6, 7, 8]).astype(int)
    # df["is_winter"] = df["month"].isin([12, 1, 2]).astype(int)


    df["break_schools"] = df["month"].isin([6, 7, 8]).astype(int)
    df["break_academia"] = df["month"].isin([7, 8, 9]).astype(int)


    checker_holidays = holidays.Poland(years=df["date"].dt.year)
    df["holiday"] = df["date"].isin(checker_holidays).astype(int)
    
    # END New Features
    ##################

    wcond_dummies = pd.get_dummies(df["wcond"], prefix="wcond", drop_first=True)
    df = pd.concat([df, wcond_dummies], axis=1)

    df = add_fourier_features(df, n_harmonics=4)

    drop_cols = ["date", "wcond", "doy"]
    df = df.drop(columns=[c for c in drop_cols if c in df.columns])

    return df

In [6]:
df_train_featured = df_train.copy()


df_train_featured = build_features(
    df_train_featured,
)

df_train_featured

,temp,atemp,hum,wind,count,month,dow,quart,week,doy_norm,...,wcond_2,wcond_3,sind1,cosd1,sind2,cosd2,sind3,cosd3,sind4,cosd4
1,9.1,13.2,79.78,10.43,982,1,5,1,1,0.002740,...,True,False,1.721336e-02,0.999852,3.442161e-02,0.999407,5.161967e-02,0.998667,6.880243e-02,0.997630
2,9.9,12.7,68.91,16.16,797,1,6,1,1,0.005479,...,True,False,3.442161e-02,0.999407,6.880243e-02,0.997630,1.031017e-01,0.994671,1.372788e-01,0.990532
3,3.1,4.5,43.29,16.14,1351,1,0,1,0,0.008219,...,False,False,5.161967e-02,0.998667,1.031017e-01,0.994671,1.543088e-01,0.988023,2.051045e-01,0.978740
4,3.2,5.6,58.45,10.42,1559,1,1,1,0,0.010959,...,False,False,6.880243e-02,0.997630,1.372788e-01,0.990532,2.051045e-01,0.978740,2.719582e-01,0.962309
5,4.3,6.5,43.26,12.15,1597,1,2,1,0,0.013699,...,False,False,8.596480e-02,0.996298,1.712931e-01,0.985220,2.553533e-01,0.966848,3.375229e-01,0.941317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,8.3,11.4,75.49,12.25,1161,12,1,4,0,0.989041,...,True,False,-6.880243e-02,0.997630,-1.372788e-01,0.990532,-2.051045e-01,0.978740,-2.719582e-01,0.962309
362,7.3,9.0,49.89,19.11,2301,12,2,4,0,0.991781,...,False,False,-5.161967e-02,0.998667,-1.031017e-01,0.994671,-1.543088e-01,0.988023,-2.051045e-01,0.978740
363,5.2,8.2,56.84,7.76,2421,12,3,4,0,0.994521,...,False,False,-3.442161e-02,0.999407,-6.880243e-02,0.997630,-1.031017e-01,0.994671,-1.372788e-01,0.990532
364,7.8,10.9,63.03,8.73,2995,12,4,4,0,0.997260,...,False,False,-1.721336e-02,0.999852,-3.442161e-02,0.999407,-5.161967e-02,0.998667,-6.880243e-02,0.997630
365,11.8,15.7,60.97,14.31,2485,12,5,4,1,1.000000,...,False,False,6.432491e-16,1.000000,1.286498e-15,1.000000,-7.347881e-16,1.000000,2.572996e-15,1.000000

In [7]:
df_test_featured = df_test.copy()

df_test_featured = build_features(
    df_test_featured, 
)

df_test_featured

,temp,atemp,hum,wind,month,dow,quart,week,doy_norm,t,...,wcond_2,wcond_3,sind1,cosd1,sind2,cosd2,sind3,cosd3,sind4,cosd4
1,10.2,13.8,68.56,12.49,1,6,1,1,0.002740,365,...,False,False,1.721336e-02,0.999852,3.442161e-02,0.999407,5.161967e-02,0.998667,6.880243e-02,0.997630
2,6.2,7.6,37.75,21.43,1,0,1,0,0.005479,366,...,False,False,3.442161e-02,0.999407,6.880243e-02,0.997630,1.031017e-01,0.994671,1.372788e-01,0.990532
3,1.1,1.3,43.68,23.77,1,1,1,0,0.008219,367,...,False,False,5.161967e-02,0.998667,1.031017e-01,0.994671,1.543088e-01,0.988023,2.051045e-01,0.978740
4,-0.6,1.0,41.04,12.01,1,2,1,0,0.010959,368,...,True,False,6.880243e-02,0.997630,1.372788e-01,0.990532,2.051045e-01,0.978740,2.719582e-01,0.962309
5,5.9,8.9,51.89,8.45,1,3,1,0,0.013699,369,...,False,False,8.596480e-02,0.996298,1.712931e-01,0.985220,2.553533e-01,0.966848,3.375229e-01,0.941317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,5.0,6.0,81.51,20.58,12,2,4,0,0.989041,725,...,False,True,-6.880243e-02,0.997630,-1.372788e-01,0.990532,-2.051045e-01,0.978740,-2.719582e-01,0.962309
362,5.4,6.3,64.64,22.76,12,3,4,0,0.991781,726,...,True,False,-5.161967e-02,0.998667,-1.031017e-01,0.994671,-1.543088e-01,0.988023,-2.051045e-01,0.978740
363,5.4,7.8,58.41,10.11,12,4,4,0,0.994521,727,...,True,False,-3.442161e-02,0.999407,-6.880243e-02,0.997630,-1.031017e-01,0.994671,-1.372788e-01,0.990532
364,5.4,7.1,74.54,8.08,12,5,4,1,0.997260,728,...,True,False,-1.721336e-02,0.999852,-3.442161e-02,0.999407,-5.161967e-02,0.998667,-6.880243e-02,0.997630
365,5.5,6.6,47.85,22.80,12,6,4,1,1.000000,729,...,False,False,6.432491e-16,1.000000,1.286498e-15,1.000000,-7.347881e-16,1.000000,2.572996e-15,1.000000

### X_[train|test] + y_[train]

In [8]:
X = df_train_featured.drop(columns=["count"]).to_numpy()

y_log = np.log1p(df_train_featured["count"].to_numpy())

In [9]:
X_test = df_test_featured.to_numpy()

# Xgboost + Optuna

In [10]:
import xgboost as xgb
import optuna

from sklearn.metrics import root_mean_squared_error as rmse
from sklearn.model_selection import GroupKFold

In [11]:
kf = GroupKFold(n_splits=6)

groups: np.ndarray = df_train["date"].dt.isocalendar().week.astype(int).to_numpy()

In [12]:
def calculate_cv(X: np.ndarray, y_log: np.ndarray, params: dict[str, float]) -> float:
    val_rmses = []
    for train_idx, val_idx in kf.split(X, y_log, groups=groups):
        model = xgb.XGBRegressor(
            **params
        )

        model.fit(X[train_idx], y_log[train_idx])
        val_pred = np.expm1(model.predict(X[val_idx]))
        y_val_orig = np.expm1(y_log[val_idx])
        val_rmses.append(rmse(y_val_orig, val_pred))

    return np.average(val_rmses)

In [13]:
def average_cvrmse_by_seeds(
        best_params: dict[str, float], 
        seeds: list[int], 
        X: np.ndarray, y_log: np.ndarray,
        verbose: bool = False,
    ) -> tuple[list[np.ndarray], float]:
    best_params_noseed = {key: val for key, val in best_params.items() if key != "random_state"}

    RMSE_cv = []

    for seed in seeds:
        print(f"seed = {seed}", end = "\t") if verbose else None

        params = {**best_params_noseed, "random_state": seed}

        rmse = calculate_cv(X, y_log, params)
        RMSE_cv.append(rmse)

        print(f"[DONE]\t{rmse:.5f}", end = "\n")  if verbose else None

    
    avg_cv_rmse = np.average(RMSE_cv)
    print(f"seed = {"END"}\t[DONE]\tMean CV = {avg_cv_rmse:.5f}")  if verbose else None

    return float(avg_cv_rmse)

In [80]:
def objective(trial: optuna.Trial) -> float:
    params = {
        "max_depth": trial.suggest_int("max_depth", 2, 10), # zmienic na 6 jeżeli pzetrenowuje
        "n_estimators": trial.suggest_int("n_estimators", 50, 800), # zmieić na 400 jeśi przetrenowuje
        "learning_rate": trial.suggest_float("learning_rate", 0.005, 0.5, log=True),

        "subsample": trial.suggest_float("subsample", 0.4, 0.8), 
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.4, 0.8),
        "colsample_bylevel": trial.suggest_float("colsample_bylevel", 0.4, 0.8),
        "colsample_bynode": trial.suggest_float("colsample_bynode", 0.4, 0.8),

        "min_child_weight": trial.suggest_int("min_child_weight", 5, 30), 
        "gamma": trial.suggest_float("gamma", 0.0, 5.0), 
        "max_delta_step": trial.suggest_float("max_delta_step", 0.0, 5.0), 

        "reg_alpha": trial.suggest_float("reg_alpha", 0.1, 50.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 0.1, 50.0, log=True),
        
        "tree_method": "hist",
        "random_state": RANDOM_STATE,
    }
    return average_cvrmse_by_seeds(
        params, 
        [seed_val for seed_val in range(5)],
        X, y_log, False
    )

In [81]:
study = optuna.create_study(
    study_name="xgb_bike",
    storage="sqlite:///params-optuna/optuna_xgb_new_features_avg_A1.db", 
    direction="minimize",
    load_if_exists=True, 
)

[I 2026-06-14 21:39:49,530] Using an existing study with name 'xgb_bike' instead of creating a new one.

In [ ]:
# study.optimize(objective, n_trials=300)

[I 2026-06-14 21:39:54,694] Trial 2489 finished with value: 582.1892665502908 and parameters: {'max_depth': 9, 'n_estimators': 634, 'learning_rate': 0.020530615967329777, 'subsample': 0.7414967966025987, 'colsample_bytree': 0.5600341293570729, 'colsample_bylevel': 0.6897049562240911, 'colsample_bynode': 0.6891307073248717, 'min_child_weight': 12, 'gamma': 0.084415671711526, 'max_delta_step': 3.9792151237446864, 'reg_alpha': 0.12357153369634645, 'reg_lambda': 9.482979544543221}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:39:56,696] Trial 2490 finished with value: 546.9355522554613 and parameters: {'max_depth': 9, 'n_estimators': 630, 'learning_rate': 0.01461116054232925, 'subsample': 0.7462830937825596, 'colsample_bytree': 0.5407807640240083, 'colsample_bylevel': 0.6959359723153843, 'colsample_bynode': 0.6886310503904735, 'min_child_weight': 5, 'gamma': 0.09626970881134214, 'max_delta_step': 3.992439684530941, 'reg_alpha': 0.10001228621985232, 'reg_lambda': 9.287069066030444}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:39:58,112] Trial 2491 finished with value: 569.5864740887557 and parameters: {'max_depth': 9, 'n_estimators': 624, 'learning_rate': 0.022985443650120344, 'subsample': 0.7440290011553412, 'colsample_bytree': 0.555821380365223, 'colsample_bylevel': 0.6908668705255242, 'colsample_bynode': 0.6966450262931475, 'min_child_weight': 5, 'gamma': 0.2316644561262084, 'max_delta_step': 3.9561179381371665, 'reg_alpha': 0.11346829266468696, 'reg_lambda': 10.214666438880858}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:00,025] Trial 2492 finished with value: 548.4740762300223 and parameters: {'max_depth': 9, 'n_estimators': 652, 'learning_rate': 0.02048061575079796, 'subsample': 0.7284245256003337, 'colsample_bytree': 0.5481110686407994, 'colsample_bylevel': 0.7072114591080952, 'colsample_bynode': 0.6886738142324851, 'min_child_weight': 5, 'gamma': 0.09576622403262068, 'max_delta_step': 4.029066331020339, 'reg_alpha': 0.1257620762302015, 'reg_lambda': 10.343854637386498}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:01,217] Trial 2493 finished with value: 852.8686072277081 and parameters: {'max_depth': 9, 'n_estimators': 639, 'learning_rate': 0.01324871618189681, 'subsample': 0.742501537430992, 'colsample_bytree': 0.5447808787779082, 'colsample_bylevel': 0.7039124211334934, 'colsample_bynode': 0.6985710567299408, 'min_child_weight': 18, 'gamma': 4.822957715847503, 'max_delta_step': 3.9723205698159116, 'reg_alpha': 0.11287689749195103, 'reg_lambda': 9.208592966704641}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:06,353] Trial 2494 finished with value: 519.6572139991147 and parameters: {'max_depth': 10, 'n_estimators': 613, 'learning_rate': 0.016878678422052606, 'subsample': 0.7345574124715815, 'colsample_bytree': 0.549094091576562, 'colsample_bylevel': 0.7047191941880694, 'colsample_bynode': 0.686729783786195, 'min_child_weight': 5, 'gamma': 0.0008294256649610768, 'max_delta_step': 4.05097401288866, 'reg_alpha': 0.12305116556831432, 'reg_lambda': 10.918784148033309}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:07,939] Trial 2495 finished with value: 560.4885915823928 and parameters: {'max_depth': 9, 'n_estimators': 619, 'learning_rate': 0.01884140602509877, 'subsample': 0.7456848570350738, 'colsample_bytree': 0.5424493731108101, 'colsample_bylevel': 0.7019924430599812, 'colsample_bynode': 0.6941262420709025, 'min_child_weight': 5, 'gamma': 0.15896171897711975, 'max_delta_step': 3.8865547301249186, 'reg_alpha': 0.13098948994933116, 'reg_lambda': 10.42165537651128}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:12,660] Trial 2496 finished with value: 517.7359686757917 and parameters: {'max_depth': 9, 'n_estimators': 616, 'learning_rate': 0.01731274137428577, 'subsample': 0.737461312106843, 'colsample_bytree': 0.5497066629801693, 'colsample_bylevel': 0.6981911359381244, 'colsample_bynode': 0.6876864908012505, 'min_child_weight': 5, 'gamma': 0.0008455553957804913, 'max_delta_step': 3.914771707581728, 'reg_alpha': 0.12486874139609151, 'reg_lambda': 11.2121973807173}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:16,576] Trial 2497 finished with value: 582.0924095518499 and parameters: {'max_depth': 10, 'n_estimators': 619, 'learning_rate': 0.020077641573523496, 'subsample': 0.7456643275518724, 'colsample_bytree': 0.5501754316199502, 'colsample_bylevel': 0.6935062287290998, 'colsample_bynode': 0.6955972737475011, 'min_child_weight': 5, 'gamma': 0.3234380781893409, 'max_delta_step': 3.904570517875934, 'reg_alpha': 0.1370261797882432, 'reg_lambda': 11.33691757937365}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:18,558] Trial 2498 finished with value: 561.7076539292966 and parameters: {'max_depth': 10, 'n_estimators': 617, 'learning_rate': 0.017446587368490307, 'subsample': 0.7376438723582345, 'colsample_bytree': 0.5542439705985702, 'colsample_bylevel': 0.6865065111601502, 'colsample_bynode': 0.7001096905286947, 'min_child_weight': 5, 'gamma': 0.15683058511898074, 'max_delta_step': 3.9396956505791123, 'reg_alpha': 0.12816988304817953, 'reg_lambda': 11.094697512056324}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:19,766] Trial 2499 finished with value: 699.1173357647997 and parameters: {'max_depth': 10, 'n_estimators': 680, 'learning_rate': 0.01812113704260155, 'subsample': 0.7450692027825496, 'colsample_bytree': 0.5493870491889179, 'colsample_bylevel': 0.6797216442109714, 'colsample_bynode': 0.6888058557425129, 'min_child_weight': 5, 'gamma': 1.8457520954619067, 'max_delta_step': 3.899271461639266, 'reg_alpha': 0.1441310608963195, 'reg_lambda': 11.511962043567634}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:21,483] Trial 2500 finished with value: 549.2718403651081 and parameters: {'max_depth': 9, 'n_estimators': 649, 'learning_rate': 0.022422264214756817, 'subsample': 0.7381508859543126, 'colsample_bytree': 0.5362591346297055, 'colsample_bylevel': 0.7066233276249066, 'colsample_bynode': 0.6871253904037454, 'min_child_weight': 5, 'gamma': 0.09794611419586491, 'max_delta_step': 3.9302314580982527, 'reg_alpha': 0.1493150234532502, 'reg_lambda': 9.254705857625584}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:22,843] Trial 2501 finished with value: 715.2491097298521 and parameters: {'max_depth': 9, 'n_estimators': 624, 'learning_rate': 0.02006203938488234, 'subsample': 0.7451594536258531, 'colsample_bytree': 0.5353848225635721, 'colsample_bylevel': 0.7009355187379154, 'colsample_bynode': 0.7004001266080343, 'min_child_weight': 5, 'gamma': 2.087031465532929, 'max_delta_step': 4.002274518575875, 'reg_alpha': 0.12705451585207583, 'reg_lambda': 11.374544767656596}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:24,057] Trial 2502 finished with value: 671.6055291221379 and parameters: {'max_depth': 9, 'n_estimators': 615, 'learning_rate': 0.01751971898839256, 'subsample': 0.73686073490301, 'colsample_bytree': 0.542823548597555, 'colsample_bylevel': 0.6952309817603776, 'colsample_bynode': 0.6918635268131528, 'min_child_weight': 5, 'gamma': 1.4617922347589878, 'max_delta_step': 3.893866674785773, 'reg_alpha': 0.1256255496833923, 'reg_lambda': 9.232288822091597}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:25,688] Trial 2503 finished with value: 572.5685098292931 and parameters: {'max_depth': 9, 'n_estimators': 616, 'learning_rate': 0.01989036607268081, 'subsample': 0.745826577178483, 'colsample_bytree': 0.5369216966579623, 'colsample_bylevel': 0.6923926864361483, 'colsample_bynode': 0.6874083082706758, 'min_child_weight': 5, 'gamma': 0.24818054905372605, 'max_delta_step': 4.071471732513647, 'reg_alpha': 0.15037177565804494, 'reg_lambda': 11.44816790506595}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:27,725] Trial 2504 finished with value: 548.9463393428197 and parameters: {'max_depth': 9, 'n_estimators': 651, 'learning_rate': 0.022956088452310886, 'subsample': 0.7347459567015798, 'colsample_bytree': 0.5445247946850282, 'colsample_bylevel': 0.7059308239147832, 'colsample_bynode': 0.6999780806218492, 'min_child_weight': 5, 'gamma': 0.0872600615358453, 'max_delta_step': 4.001370641716739, 'reg_alpha': 0.12628325760166517, 'reg_lambda': 10.584610121365372}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:32,105] Trial 2505 finished with value: 516.909104740787 and parameters: {'max_depth': 10, 'n_estimators': 621, 'learning_rate': 0.018472185221627725, 'subsample': 0.7436506149083003, 'colsample_bytree': 0.5433308101664225, 'colsample_bylevel': 0.6998947559217094, 'colsample_bynode': 0.685338514549724, 'min_child_weight': 5, 'gamma': 0.0013970277924823414, 'max_delta_step': 3.9425122984817307, 'reg_alpha': 0.15119371028079862, 'reg_lambda': 9.168591194623987}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:33,701] Trial 2506 finished with value: 563.4644299506133 and parameters: {'max_depth': 9, 'n_estimators': 636, 'learning_rate': 0.020649092124641066, 'subsample': 0.7453709343495116, 'colsample_bytree': 0.5408789013993645, 'colsample_bylevel': 0.67968482843261, 'colsample_bynode': 0.6947771422784391, 'min_child_weight': 5, 'gamma': 0.20390992732340932, 'max_delta_step': 3.827412165951986, 'reg_alpha': 0.15193542273553026, 'reg_lambda': 9.022128219415682}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:34,851] Trial 2507 finished with value: 680.6627176026793 and parameters: {'max_depth': 9, 'n_estimators': 615, 'learning_rate': 0.0187062569347492, 'subsample': 0.746762328640871, 'colsample_bytree': 0.5333220091009583, 'colsample_bylevel': 0.709024934919774, 'colsample_bynode': 0.7023106758138264, 'min_child_weight': 5, 'gamma': 1.63109868017362, 'max_delta_step': 3.845462415581311, 'reg_alpha': 0.15509812997067565, 'reg_lambda': 9.284678479154449}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:36,843] Trial 2508 finished with value: 547.5074269905359 and parameters: {'max_depth': 9, 'n_estimators': 662, 'learning_rate': 0.02194916014833299, 'subsample': 0.746176675936326, 'colsample_bytree': 0.5342387491416307, 'colsample_bylevel': 0.6714291525927425, 'colsample_bynode': 0.6847637551209831, 'min_child_weight': 5, 'gamma': 0.09276654161258033, 'max_delta_step': 3.873962931791274, 'reg_alpha': 0.1558399499430825, 'reg_lambda': 8.868893275336935}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:38,157] Trial 2509 finished with value: 655.0402713497058 and parameters: {'max_depth': 9, 'n_estimators': 782, 'learning_rate': 0.020959581563838436, 'subsample': 0.7404362387817626, 'colsample_bytree': 0.5491032705208354, 'colsample_bylevel': 0.6969136640542611, 'colsample_bynode': 0.6937661019241598, 'min_child_weight': 5, 'gamma': 1.272713379385639, 'max_delta_step': 3.9456867902103583, 'reg_alpha': 0.13887000451199066, 'reg_lambda': 9.081758876522025}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:39,872] Trial 2510 finished with value: 549.1286081007659 and parameters: {'max_depth': 10, 'n_estimators': 604, 'learning_rate': 0.01857632310939477, 'subsample': 0.7390764227638257, 'colsample_bytree': 0.5520788182306696, 'colsample_bylevel': 0.6905095279153094, 'colsample_bynode': 0.6866179965329932, 'min_child_weight': 5, 'gamma': 0.10174615633111293, 'max_delta_step': 3.9292902254025845, 'reg_alpha': 0.1384448760063779, 'reg_lambda': 10.238504475086215}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:41,036] Trial 2511 finished with value: 790.5177009917633 and parameters: {'max_depth': 10, 'n_estimators': 677, 'learning_rate': 0.018912525003274165, 'subsample': 0.7457373948234783, 'colsample_bytree': 0.5443889407657985, 'colsample_bylevel': 0.6995324396907068, 'colsample_bynode': 0.6861453939859938, 'min_child_weight': 5, 'gamma': 3.2962071607032786, 'max_delta_step': 3.9725299734907193, 'reg_alpha': 0.11143470649765674, 'reg_lambda': 11.93456832932613}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:42,575] Trial 2512 finished with value: 582.1335345667705 and parameters: {'max_depth': 9, 'n_estimators': 627, 'learning_rate': 0.02347231907474181, 'subsample': 0.7311103943513432, 'colsample_bytree': 0.5403678147657761, 'colsample_bylevel': 0.6849133614636872, 'colsample_bynode': 0.7006876948319347, 'min_child_weight': 5, 'gamma': 0.3501149401742265, 'max_delta_step': 4.00796861553429, 'reg_alpha': 0.149845399349242, 'reg_lambda': 10.286723216541315}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:44,445] Trial 2513 finished with value: 546.7343509011444 and parameters: {'max_depth': 9, 'n_estimators': 617, 'learning_rate': 0.0209124435842742, 'subsample': 0.7363272257552234, 'colsample_bytree': 0.5537889960290007, 'colsample_bylevel': 0.7092570085242167, 'colsample_bynode': 0.6939869003899513, 'min_child_weight': 5, 'gamma': 0.08725908340748609, 'max_delta_step': 3.875558538156963, 'reg_alpha': 0.1328583247982431, 'reg_lambda': 8.997963746148748}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:46,116] Trial 2514 finished with value: 563.993827820612 and parameters: {'max_depth': 10, 'n_estimators': 640, 'learning_rate': 0.01788679086824726, 'subsample': 0.745270332582254, 'colsample_bytree': 0.5509229753166369, 'colsample_bylevel': 0.6965326086363454, 'colsample_bynode': 0.6817995043935525, 'min_child_weight': 5, 'gamma': 0.18411831819786348, 'max_delta_step': 4.037243641238427, 'reg_alpha': 0.10066859366896391, 'reg_lambda': 10.448268343325497}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:48,255] Trial 2515 finished with value: 548.8918711974627 and parameters: {'max_depth': 9, 'n_estimators': 611, 'learning_rate': 0.022805686243745817, 'subsample': 0.7377780028479428, 'colsample_bytree': 0.5344121719252188, 'colsample_bylevel': 0.6903119004751734, 'colsample_bynode': 0.7044198519679896, 'min_child_weight': 5, 'gamma': 0.0858559316336433, 'max_delta_step': 4.041162141012895, 'reg_alpha': 0.12136157948717623, 'reg_lambda': 12.054264155085102}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:49,732] Trial 2516 finished with value: 579.5463977468308 and parameters: {'max_depth': 10, 'n_estimators': 627, 'learning_rate': 0.016629233439829645, 'subsample': 0.728065858318305, 'colsample_bytree': 0.544944849555566, 'colsample_bylevel': 0.7085217493463492, 'colsample_bynode': 0.683473278408644, 'min_child_weight': 5, 'gamma': 0.26413395798631706, 'max_delta_step': 3.937538365447417, 'reg_alpha': 0.15479479653012287, 'reg_lambda': 12.176756338522985}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:54,165] Trial 2517 finished with value: 517.615537874997 and parameters: {'max_depth': 9, 'n_estimators': 629, 'learning_rate': 0.01983960883916177, 'subsample': 0.7445393690818983, 'colsample_bytree': 0.5528031132601076, 'colsample_bylevel': 0.701640043149605, 'colsample_bynode': 0.6939260409049949, 'min_child_weight': 5, 'gamma': 0.0026759278241737967, 'max_delta_step': 4.052307249967785, 'reg_alpha': 0.11357689104207712, 'reg_lambda': 9.005661230967641}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:56,679] Trial 2518 finished with value: 558.3398797603498 and parameters: {'max_depth': 9, 'n_estimators': 616, 'learning_rate': 0.17213564390019234, 'subsample': 0.7367793471192555, 'colsample_bytree': 0.5521092496033377, 'colsample_bylevel': 0.6953955870050071, 'colsample_bynode': 0.4838100975001375, 'min_child_weight': 5, 'gamma': 0.0020473103306228838, 'max_delta_step': 3.8436480531262722, 'reg_alpha': 0.11227937690703821, 'reg_lambda': 9.147655679731832}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:58,338] Trial 2519 finished with value: 561.8718047924295 and parameters: {'max_depth': 10, 'n_estimators': 630, 'learning_rate': 0.018669105214799822, 'subsample': 0.7279420815550545, 'colsample_bytree': 0.5353798136150677, 'colsample_bylevel': 0.6834894826681963, 'colsample_bynode': 0.7031611334895475, 'min_child_weight': 5, 'gamma': 0.17389609760372465, 'max_delta_step': 3.888024930385099, 'reg_alpha': 0.11493490029862242, 'reg_lambda': 8.782002052907071}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:40:59,972] Trial 2520 finished with value: 593.1627996837622 and parameters: {'max_depth': 9, 'n_estimators': 613, 'learning_rate': 0.01978080207357968, 'subsample': 0.738816990839635, 'colsample_bytree': 0.5412925644237737, 'colsample_bylevel': 0.7009792731157621, 'colsample_bynode': 0.696280253367984, 'min_child_weight': 12, 'gamma': 0.17106975747399408, 'max_delta_step': 3.963033976578715, 'reg_alpha': 0.11267797602970009, 'reg_lambda': 8.772431250649724}. Best is trial 2282 with value: 516.2504570996613.
[I 2026-06-14 21:41:05,604] Trial 2521 finished with value: 515.9164453177711 and parameters: {'max_depth': 9, 'n_estimators': 641, 'learning_rate': 0.016606268852020697, 'subsample': 0.7301967735659615, 'colsample_bytree': 0.5529438472773135, 'colsample_bylevel': 0.699418381967412, 'colsample_bynode': 0.7053312700604034, 'min_child_weight': 5, 'gamma': 0.0017354516241315722, 'max_delta_step': 4.040439563914634, 'reg_alpha': 0.10033260608873593, 'reg_lambda': 9.036524616110492}. Best is trial 2521 with value: 515.9164453177711.
[I 2026-06-14 21:41:08,057] Trial 2522 finished with value: 545.0232239813201 and parameters: {'max_depth': 9, 'n_estimators': 661, 'learning_rate': 0.016783611800240312, 'subsample': 0.7295083288374127, 'colsample_bytree': 0.5469995449690086, 'colsample_bylevel': 0.6874734576372801, 'colsample_bynode': 0.705602869253271, 'min_child_weight': 5, 'gamma': 0.08120378852433005, 'max_delta_step': 3.929876497691303, 'reg_alpha': 0.1002008362626738, 'reg_lambda': 8.982459990436189}. Best is trial 2521 with value: 515.9164453177711.
[I 2026-06-14 21:41:13,461] Trial 2523 finished with value: 517.2635698614039 and parameters: {'max_depth': 9, 'n_estimators': 641, 'learning_rate': 0.016378350559085833, 'subsample': 0.7292772640814742, 'colsample_bytree': 0.5525554900807167, 'colsample_bylevel': 0.7018796024156618, 'colsample_bynode': 0.7050451912345413, 'min_child_weight': 5, 'gamma': 0.0007898264925408618, 'max_delta_step': 4.003653378815149, 'reg_alpha': 0.11024909364120404, 'reg_lambda': 10.199776159103846}. Best is trial 2521 with value: 515.9164453177711.
[I 2026-06-14 21:41:15,422] Trial 2524 finished with value: 570.7125638214702 and parameters: {'max_depth': 9, 'n_estimators': 664, 'learning_rate': 0.016039886638618876, 'subsample': 0.7275271717838592, 'colsample_bytree': 0.5369219252770138, 'colsample_bylevel': 0.676597836364753, 'colsample_bynode': 0.7039302587157138, 'min_child_weight': 5, 'gamma': 0.24798885562921963, 'max_delta_step': 3.798299149974835, 'reg_alpha': 0.10176885460127821, 'reg_lambda': 9.29483929449499}. Best is trial 2521 with value: 515.9164453177711.
[I 2026-06-14 21:41:17,316] Trial 2525 finished with value: 595.9779509090129 and parameters: {'max_depth': 9, 'n_estimators': 647, 'learning_rate': 0.015857974582561198, 'subsample': 0.7369801323501247, 'colsample_bytree': 0.5534797783483802, 'colsample_bylevel': 0.6976761290839134, 'colsample_bynode': 0.7070551832396144, 'min_child_weight': 5, 'gamma': 0.4540198079645847, 'max_delta_step': 3.9424433654087996, 'reg_alpha': 0.11040960516179393, 'reg_lambda': 10.285019866071087}. Best is trial 2521 with value: 515.9164453177711.

In [142]:
print(f"[XGBoost + optuna]\nruns_params={study.best_params}\nbest_value={study.best_value}")

[XGBoost + optuna]
runs_params={'max_depth': 10, 'n_estimators': 673, 'learning_rate': 0.016275472726490006, 'subsample': 0.733562186336755, 'colsample_bytree': 0.5509434659946164, 'colsample_bylevel': 0.7037245542968691, 'colsample_bynode': 0.7010598868099925, 'min_child_weight': 5, 'gamma': 0.001268101935957147, 'max_delta_step': 3.779634460282497, 'reg_alpha': 0.10013041967270879, 'reg_lambda': 10.479085696096853}
best_value=514.7725556781845

In [159]:
best_params = study.best_params

best_params=dict(
    zip(
        ['max_depth', 'n_estimators', 'learning_rate', 'subsample', 'colsample_bytree', 'colsample_bylevel', 'colsample_bynode', 'min_child_weight', 'gamma', 'max_delta_step', 'reg_alpha', 'reg_lambda', 'tree_method', 'random_state'],
        [6,420,0.0300,0.6080,0.5460,0.7600,0.5870,5,0.0010,1.3000,0.1400,3.8780,'hist',42,]
,
    )
)

best_params = {**best_params, "tree_method": "hist", "random_state": RANDOM_STATE,}

In [160]:
print(f"best_params = {best_params}")

best_params = {'max_depth': 6, 'n_estimators': 420, 'learning_rate': 0.03, 'subsample': 0.608, 'colsample_bytree': 0.546, 'colsample_bylevel': 0.76, 'colsample_bynode': 0.587, 'min_child_weight': 5, 'gamma': 0.001, 'max_delta_step': 1.3, 'reg_alpha': 0.14, 'reg_lambda': 3.878, 'tree_method': 'hist', 'random_state': 42}

### Final Validation + Prediction

In [137]:
def average_multiple_models(
        best_params: dict[str, float], 
        seeds: list[int], 
        X: np.ndarray, y_log: np.ndarray, X_test: np.ndarray,
        verbose: bool = False,
    ) -> tuple[list[np.ndarray], float]:
    best_params_noseed = {key: val for key, val in best_params.items() if key != "random_state"}

    preds = []
    RMSE_cv = []

    for seed in seeds:
        print(f"seed = {seed}", end = "\t") if verbose else None

        params = {**best_params_noseed, "random_state": seed}

        model = xgb.XGBRegressor(**params)

        model.fit(X, y_log)
        pred = np.expm1(model.predict(X_test))
        preds.append(pred)

        rmse = calculate_cv(X, y_log, params)
        RMSE_cv.append(rmse)

        print(f"[DONE]\t{rmse:.5f}", end = "\n")  if verbose else None

    
    avg_cv_rmse = np.average(RMSE_cv)
    print(f"seed = {"END"}\t[MEAN]\t{avg_cv_rmse:.5f}")  if verbose else None

    return preds, avg_cv_rmse

In [138]:
multiple_preds, avg_rmse_cv = average_multiple_models(
    best_params, 
    # [seed_val for seed_val in range(5)],
    [42],
    X, y_log, X_test, 
    verbose=True
)

seed = 42	[DONE]	520.55161
seed = END	[MEAN]	520.55161

In [139]:
pred = np.mean(multiple_preds, axis=0)

len(pred)

365

# Generating Model Params

In [140]:
def print_model(model_type: str, params: dict[str, float], validation_rmse: float, columns_train_datset: list[str]) -> None:
    print(f"[{model_type}]", end="\n")
    print(f"V-RMSE: {validation_rmse:.2f}", end = "\n")

    print(f"params=[", end = "")
    for param_name, param_value in params.items():
        if type(param_value) is not str and type(param_value) is not int:
            print(f"{param_value:.4f}", end = ",")
        elif type(param_value) is not str:
            print(f"{param_value}", end = ",")
        else:
            print(f"'{param_value}'", end = ",")
    print(f"]", end = "\n")
    
    print(f"columns=[", end = "")
    for col_name in columns_train_datset:
        print(f"{col_name}", end = ",")
    print(f"]", end = "")

In [154]:
print_model(f"XGBoost + Optuna + Models Average (1) (seed=42) + round (1)", best_params, avg_rmse_cv, df_train_featured.columns.to_list())

[XGBoost + Optuna + Models Average (1) (seed=42) + round (1)]
V-RMSE: 520.55
params=[6,420,0.0300,0.6080,0.5460,0.7600,0.5870,5,0.0010,1.3000,0.1400,3.8780,'hist',42,]
columns=[temp,atemp,hum,wind,count,month,dow,quart,week,doy_norm,t,temp2,temp3,hum2,wind2,temp-atemp,tempxhum,tempxwind,atempxhum,humxwind,wcondxtemp,break_schools,break_academia,holiday,wcond_2,wcond_3,sind1,cosd1,sind2,cosd2,sind3,cosd3,sind4,cosd4,]

# Submission Generator

In [155]:
from scripts.save_submission import save_submission_csv

In [156]:
df_date = pd.read_csv(f"data-00-raw/bike_test.csv", parse_dates=["date"])

df_date["date"]

0     2023-01-01
1     2023-01-02
2     2023-01-03
3     2023-01-04
4     2023-01-05
         ...
360   2023-12-27
361   2023-12-28
362   2023-12-29
363   2023-12-30
364   2023-12-31
Name: date, Length: 365, dtype: datetime64[us]

In [157]:
df_submission = pd.DataFrame({"date": df_date["date"], "pred": pred})

df_submission["pred"] = df_submission["pred"].round(1)

df_submission

          date         pred
0   2023-01-01  1282.500000
1   2023-01-02  1567.300049
2   2023-01-03  1309.400024
3   2023-01-04  1377.199951
4   2023-01-05  1798.300049
..         ...          ...
360 2023-12-27   867.000000
361 2023-12-28  1448.800049
362 2023-12-29  1921.900024
363 2023-12-30  1354.099976
364 2023-12-31  1645.099976

[365 rows x 2 columns]

In [158]:
save_submission_csv(df_submission)