In [40]:
import pandas as pd
import numpy as np

RANDOM_STATE = 42

In [41]:
df_train = pd.read_csv(f"data-01-processed/ridge_regression_train.csv", index_col=[0])

df_train

,temp,atemp,hum,wind,temp_sq,hum_sq,wind_sq,temp_x_hum,temp_x_wind,atemp_x_hum,...,dayofyear,sin_doy_1,cos_doy_1,sin_doy_2,cos_doy_2,sin_doy_3,cos_doy_3,wcond_2,wcond_3,count
1,9.1,13.2,79.78,10.43,82.81,6364.8484,108.7849,725.998,94.913,1053.096,...,1,1.721336e-02,0.999852,3.442161e-02,0.999407,5.161967e-02,0.998667,True,False,982
2,9.9,12.7,68.91,16.16,98.01,4748.5881,261.1456,682.209,159.984,875.157,...,2,3.442161e-02,0.999407,6.880243e-02,0.997630,1.031017e-01,0.994671,True,False,797
3,3.1,4.5,43.29,16.14,9.61,1874.0241,260.4996,134.199,50.034,194.805,...,3,5.161967e-02,0.998667,1.031017e-01,0.994671,1.543088e-01,0.988023,False,False,1351
4,3.2,5.6,58.45,10.42,10.24,3416.4025,108.5764,187.040,33.344,327.320,...,4,6.880243e-02,0.997630,1.372788e-01,0.990532,2.051045e-01,0.978740,False,False,1559
5,4.3,6.5,43.26,12.15,18.49,1871.4276,147.6225,186.018,52.245,281.190,...,5,8.596480e-02,0.996298,1.712931e-01,0.985220,2.553533e-01,0.966848,False,False,1597
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,8.3,11.4,75.49,12.25,68.89,5698.7401,150.0625,626.567,101.675,860.586,...,361,-6.880243e-02,0.997630,-1.372788e-01,0.990532,-2.051045e-01,0.978740,True,False,1161
362,7.3,9.0,49.89,19.11,53.29,2489.0121,365.1921,364.197,139.503,449.010,...,362,-5.161967e-02,0.998667,-1.031017e-01,0.994671,-1.543088e-01,0.988023,False,False,2301
363,5.2,8.2,56.84,7.76,27.04,3230.7856,60.2176,295.568,40.352,466.088,...,363,-3.442161e-02,0.999407,-6.880243e-02,0.997630,-1.031017e-01,0.994671,False,False,2421
364,7.8,10.9,63.03,8.73,60.84,3972.7809,76.2129,491.634,68.094,687.027,...,364,-1.721336e-02,0.999852,-3.442161e-02,0.999407,-5.161967e-02,0.998667,False,False,2995
365,11.8,15.7,60.97,14.31,139.24,3717.3409,204.7761,719.446,168.858,957.229,...,365,6.432491e-16,1.000000,1.286498e-15,1.000000,-7.347881e-16,1.000000,False,False,2485

# Cross Validation

In [42]:
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

from scripts.find_alpha_ridge import cross_validate_ridge

In [43]:
X = df_train[[col for col in df_train.columns if col != "count"]].to_numpy()

y = df_train["count"].to_numpy()

alphas = np.logspace(-6, 1, 1000)

kf = KFold(n_splits=20, shuffle=True, random_state=RANDOM_STATE)

In [44]:
results = cross_validate_ridge(
    X = X,
    y = y,
    alphas=alphas,
    kf = kf
)

[Fold]: 0
	[ALPHA]: 0
	[ALPHA]: 1
	[ALPHA]: 2
	[ALPHA]: 3
	[ALPHA]: 4
	[ALPHA]: 5
	[ALPHA]: 6
	[ALPHA]: 7
	[ALPHA]: 8
	[ALPHA]: 9
	[ALPHA]: 10
	[ALPHA]: 11
	[ALPHA]: 12
	[ALPHA]: 13
	[ALPHA]: 14
	[ALPHA]: 15
	[ALPHA]: 16
	[ALPHA]: 17
	[ALPHA]: 18
	[ALPHA]: 19
	[ALPHA]: 20
	[ALPHA]: 21
	[ALPHA]: 22
	[ALPHA]: 23
	[ALPHA]: 24
	[ALPHA]: 25
	[ALPHA]: 26
	[ALPHA]: 27
	[ALPHA]: 28
	[ALPHA]: 29
	[ALPHA]: 30
	[ALPHA]: 31
	[ALPHA]: 32
	[ALPHA]: 33
	[ALPHA]: 34
	[ALPHA]: 35
	[ALPHA]: 36
	[ALPHA]: 37
	[ALPHA]: 38
	[ALPHA]: 39
	[ALPHA]: 40
	[ALPHA]: 41
	[ALPHA]: 42
	[ALPHA]: 43
	[ALPHA]: 44
	[ALPHA]: 45
	[ALPHA]: 46
	[ALPHA]: 47
	[ALPHA]: 48
	[ALPHA]: 49
	[ALPHA]: 50
	[ALPHA]: 51
	[ALPHA]: 52
	[ALPHA]: 53
	[ALPHA]: 54
	[ALPHA]: 55
	[ALPHA]: 56
	[ALPHA]: 57
	[ALPHA]: 58
	[ALPHA]: 59
	[ALPHA]: 60
	[ALPHA]: 61
	[ALPHA]: 62
	[ALPHA]: 63
	[ALPHA]: 64
	[ALPHA]: 65
	[ALPHA]: 66
	[ALPHA]: 67
	[ALPHA]: 68
	[ALPHA]: 69
	[ALPHA]: 70
	[ALPHA]: 71
	[ALPHA]: 72
	[ALPHA]: 73
	[ALPHA]: 74
	[ALPHA]: 75
	[ALPHA]: 76
	[ALPHA]: 77
	[ALPHA]: 78
	[ALPHA]: 79
	[ALPHA]: 80
	[ALPHA]: 81
	[ALPHA]: 82
	[ALPHA]: 83
	[ALPHA]: 84
	[ALPHA]: 85
	[ALPHA]: 86
	[ALPHA]: 87
	[ALPHA]: 88
	[ALPHA]: 89
	[ALPHA]: 90
	[ALPHA]: 91
	[ALPHA]: 92
	[ALPHA]: 93
	[ALPHA]: 94
	[ALPHA]: 95
	[ALPHA]: 96
	[ALPHA]: 97
	[ALPHA]: 98
	[ALPHA]: 99
	[ALPHA]: 100
	[ALPHA]: 101
	[ALPHA]: 102
	[ALPHA]: 103
	[ALPHA]: 104
	[ALPHA]: 105
	[ALPHA]: 106
	[ALPHA]: 107
	[ALPHA]: 108
	[ALPHA]: 109
	[ALPHA]: 110
	[ALPHA]: 111
	[ALPHA]: 112
	[ALPHA]: 113
	[ALPHA]: 114
	[ALPHA]: 115
	[ALPHA]: 116
	[ALPHA]: 117
	[ALPHA]: 118
	[ALPHA]: 119
	[ALPHA]: 120
	[ALPHA]: 121
	[ALPHA]: 122
	[ALPHA]: 123
	[ALPHA]: 124
	[ALPHA]: 125
	[ALPHA]: 126
	[ALPHA]: 127
	[ALPHA]: 128
	[ALPHA]: 129
	[ALPHA]: 130
	[ALPHA]: 131
	[ALPHA]: 132
	[ALPHA]: 133
	[ALPHA]: 134
	[ALPHA]: 135
	[ALPHA]: 136
	[ALPHA]: 137
	[ALPHA]: 138
	[ALPHA]: 139
	[ALPHA]: 140
	[ALPHA]: 141
	[ALPHA]: 142
	[ALPHA]: 143
	[ALPHA]: 144
	[ALPHA]: 145
	[ALPHA]: 146
	[ALPHA]: 147
	[ALPHA]: 148
	[ALPHA]: 149
	[ALPHA]: 150
	[ALPHA]: 151
	[ALPHA]: 152
	[ALPHA]: 153
	[ALPHA]: 154
	[ALPHA]: 155
	[ALPHA]: 156
	[ALPHA]: 157
	[ALPHA]: 158
	[ALPHA]: 159
	[ALPHA]: 160
	[ALPHA]: 161
	[ALPHA]: 162
	[ALPHA]: 163
	[ALPHA]: 164
	[ALPHA]: 165
	[ALPHA]: 166
	[ALPHA]: 167
	[ALPHA]: 168
	[ALPHA]: 169
	[ALPHA]: 170
	[ALPHA]: 171
	[ALPHA]: 172
	[ALPHA]: 173
	[ALPHA]: 174
	[ALPHA]: 175
	[ALPHA]: 176
	[ALPHA]: 177
	[ALPHA]: 178
	[ALPHA]: 179
	[ALPHA]: 180
	[ALPHA]: 181
	[ALPHA]: 182
	[ALPHA]: 183
	[ALPHA]: 184
	[ALPHA]: 185
	[ALPHA]: 186
	[ALPHA]: 187
	[ALPHA]: 188
	[ALPHA]: 189
	[ALPHA]: 190
	[ALPHA]: 191
	[ALPHA]: 192
	[ALPHA]: 193
	[ALPHA]: 194
	[ALPHA]: 195
	[ALPHA]: 196
	[ALPHA]: 197
	[ALPHA]: 198
	[ALPHA]: 199
	[ALPHA]: 200
	[ALPHA]: 201
	[ALPHA]: 202
	[ALPHA]: 203
	[ALPHA]: 204
	[ALPHA]: 205
	[ALPHA]: 206
	[ALPHA]: 207
	[ALPHA]: 208
	[ALPHA]: 209
	[ALPHA]: 210
	[ALPHA]: 211
	[ALPHA]: 212
	[ALPHA]: 213
	[ALPHA]: 214
	[ALPHA]: 215
	[ALPHA]: 216
	[ALPHA]: 217
	[ALPHA]: 218
	[ALPHA]: 219
	[ALPHA]: 220
	[ALPHA]: 221
	[ALPHA]: 222
	[ALPHA]: 223
	[ALPHA]: 224
	[ALPHA]: 225
	[ALPHA]: 226
	[ALPHA]: 227
	[ALPHA]: 228
	[ALPHA]: 229
	[ALPHA]: 230
	[ALPHA]: 231
	[ALPHA]: 232
	[ALPHA]: 233
	[ALPHA]: 234
	[ALPHA]: 235
	[ALPHA]: 236
	[ALPHA]: 237
	[ALPHA]: 238
	[ALPHA]: 239
	[ALPHA]: 240
	[ALPHA]: 241
	[ALPHA]: 242
	[ALPHA]: 243
	[ALPHA]: 244
	[ALPHA]: 245
	[ALPHA]: 246
	[ALPHA]: 247
	[ALPHA]: 248
	[ALPHA]: 249
	[ALPHA]: 250
	[ALPHA]: 251
	[ALPHA]: 252
	[ALPHA]: 253
	[ALPHA]: 254
	[ALPHA]: 255
	[ALPHA]: 256
	[ALPHA]: 257
	[ALPHA]: 258
	[ALPHA]: 259
	[ALPHA]: 260
	[ALPHA]: 261
	[ALPHA]: 262
	[ALPHA]: 263
	[ALPHA]: 264
	[ALPHA]: 265
	[ALPHA]: 266
	[ALPHA]: 267
	[ALPHA]: 268
	[ALPHA]: 269
	[ALPHA]: 270
	[ALPHA]: 271
	[ALPHA]: 272
	[ALPHA]: 273
	[ALPHA]: 274
	[ALPHA]: 275
	[ALPHA]: 276
	[ALPHA]: 277
	[ALPHA]: 278
	[ALPHA]: 279
	[ALPHA]: 280
	[ALPHA]: 281
	[ALPHA]: 282
	[ALPHA]: 283
	[ALPHA]: 284
	[ALPHA]: 285
	[ALPHA]: 286
	[ALPHA]: 287
	[ALPHA]: 288
	[ALPHA]: 289
	[ALPHA]: 290
	[ALPHA]: 291
	[ALPHA]: 292
	[ALPHA]: 293
	[ALPHA]: 294
	[ALPHA]: 295
	[ALPHA]: 296
	[ALPHA]: 297
	[ALPHA]: 298
	[ALPHA]: 299
	[ALPHA]: 300
	[ALPHA]: 301
	[ALPHA]: 302
	[ALPHA]: 303
	[ALPHA]: 304
	[ALPHA]: 305
	[ALPHA]: 306
	[ALPHA]: 307
	[ALPHA]: 308
	[ALPHA]: 309
	[ALPHA]: 310
	[ALPHA]: 311
	[ALPHA]: 312
	[ALPHA]: 313
	[ALPHA]: 314
	[ALPHA]: 315
	[ALPHA]: 316
	[ALPHA]: 317
	[ALPHA]: 318
	[ALPHA]: 319
	[ALPHA]: 320
	[ALPHA]: 321
	[ALPHA]: 322
	[ALPHA]: 323
	[ALPHA]: 324
	[ALPHA]: 325
	[ALPHA]: 326
	[ALPHA]: 327
	[ALPHA]: 328
	[ALPHA]: 329
	[ALPHA]: 330
	[ALPHA]: 331
	[ALPHA]: 332
	[ALPHA]: 333
	[ALPHA]: 334
	[ALPHA]: 335
	[ALPHA]: 336
	[ALPHA]: 337
	[ALPHA]: 338
	[ALPHA]: 339
	[ALPHA]: 340
	[ALPHA]: 341
	[ALPHA]: 342
	[ALPHA]: 343
	[ALPHA]: 344
	[ALPHA]: 345
	[ALPHA]: 346
	[ALPHA]: 347
	[ALPHA]: 348
	[ALPHA]: 349
	[ALPHA]: 350
	[ALPHA]: 351
	[ALPHA]: 352
	[ALPHA]: 353
	[ALPHA]: 354
	[ALPHA]: 355
	[ALPHA]: 356
	[ALPHA]: 357
	[ALPHA]: 358
	[ALPHA]: 359
	[ALPHA]: 360
	[ALPHA]: 361
	[ALPHA]: 362
	[ALPHA]: 363
	[ALPHA]: 364
	[ALPHA]: 365
	[ALPHA]: 366
	[ALPHA]: 367
	[ALPHA]: 368
	[ALPHA]: 369
	[ALPHA]: 370
	[ALPHA]: 371
	[ALPHA]: 372
	[ALPHA]: 373
	[ALPHA]: 374
	[ALPHA]: 375
	[ALPHA]: 376
	[ALPHA]: 377
	[ALPHA]: 378
	[ALPHA]: 379
	[ALPHA]: 380
	[ALPHA]: 381
	[ALPHA]: 382
	[ALPHA]: 383
	[ALPHA]: 384
	[ALPHA]: 385
	[ALPHA]: 386
	[ALPHA]: 387
	[ALPHA]: 388
	[ALPHA]: 389
	[ALPHA]: 390
	[ALPHA]: 391
	[ALPHA]: 392
	[ALPHA]: 393
	[ALPHA]: 394
	[ALPHA]: 395
	[ALPHA]: 396
	[ALPHA]: 397
	[ALPHA]: 398
	[ALPHA]: 399
	[ALPHA]: 400
	[ALPHA]: 401
	[ALPHA]: 402
	[ALPHA]: 403
	[ALPHA]: 404
	[ALPHA]: 405
	[ALPHA]: 406
	[ALPHA]: 407
	[ALPHA]: 408
	[ALPHA]: 409
	[ALPHA]: 410
	[ALPHA]: 411
	[ALPHA]: 412
	[ALPHA]: 413
	[ALPHA]: 414
	[ALPHA]: 415
	[ALPHA]: 416
	[ALPHA]: 417
	[ALPHA]: 418
	[ALPHA]: 419
	[ALPHA]: 420
	[ALPHA]: 421
	[ALPHA]: 422
	[ALPHA]: 423
	[ALPHA]: 424
	[ALPHA]: 425
	[ALPHA]: 426
	[ALPHA]: 427
	[ALPHA]: 428
	[ALPHA]: 429
	[ALPHA]: 430
	[ALPHA]: 431
	[ALPHA]: 432
	[ALPHA]: 433
	[ALPHA]: 434
	[ALPHA]: 435
	[ALPHA]: 436
	[ALPHA]: 437
	[ALPHA]: 438
	[ALPHA]: 439
	[ALPHA]: 440
	[ALPHA]: 441
	[ALPHA]: 442
	[ALPHA]: 443
	[ALPHA]: 444
	[ALPHA]: 445
	[ALPHA]: 446
	[ALPHA]: 447
	[ALPHA]: 448
	[ALPHA]: 449
	[ALPHA]: 450
	[ALPHA]: 451
	[ALPHA]: 452
	[ALPHA]: 453
	[ALPHA]: 454
	[ALPHA]: 455
	[ALPHA]: 456
	[ALPHA]: 457
	[ALPHA]: 458
	[ALPHA]: 459
	[ALPHA]: 460
	[ALPHA]: 461
	[ALPHA]: 462
	[ALPHA]: 463
	[ALPHA]: 464
	[ALPHA]: 465
	[ALPHA]: 466
	[ALPHA]: 467
	[ALPHA]: 468
	[ALPHA]: 469
	[ALPHA]: 470
	[ALPHA]: 471
	[ALPHA]: 472
	[ALPHA]: 473
	[ALPHA]: 474
	[ALPHA]: 475
	[ALPHA]: 476
	[ALPHA]: 477
	[ALPHA]: 478
	[ALPHA]: 479
	[ALPHA]: 480
	[ALPHA]: 481
	[ALPHA]: 482
	[ALPHA]: 483
	[ALPHA]: 484
	[ALPHA]: 485
	[ALPHA]: 486
	[ALPHA]: 487
	[ALPHA]: 488
	[ALPHA]: 489
	[ALPHA]: 490
	[ALPHA]: 491
	[ALPHA]: 492
	[ALPHA]: 493
	[ALPHA]: 494
	[ALPHA]: 495
	[ALPHA]: 496
	[ALPHA]: 497
	[ALPHA]: 498
	[ALPHA]: 499
	[ALPHA]: 500
	[ALPHA]: 501
	[ALPHA]: 502
	[ALPHA]: 503
	[ALPHA]: 504
	[ALPHA]: 505
	[ALPHA]: 506
	[ALPHA]: 507
	[ALPHA]: 508
	[ALPHA]: 509
	[ALPHA]: 510
	[ALPHA]: 511
	[ALPHA]: 512
	[ALPHA]: 513
	[ALPHA]: 514
	[ALPHA]: 515
	[ALPHA]: 516
	[ALPHA]: 517
	[ALPHA]: 518
	[ALPHA]: 519
	[ALPHA]: 520
	[ALPHA]: 521
	[ALPHA]: 522
	[ALPHA]: 523
	[ALPHA]: 524
	[ALPHA]: 525
	[ALPHA]: 526
	[ALPHA]: 527
	[ALPHA]: 528
	[ALPHA]: 529
	[ALPHA]: 530
	[ALPHA]: 531
	[ALPHA]: 532
	[ALPHA]: 533
	[ALPHA]: 534
	[ALPHA]: 535
	[ALPHA]: 536
	[ALPHA]: 537
	[ALPHA]: 538
	[ALPHA]: 539
	[ALPHA]: 540
	[ALPHA]: 541
	[ALPHA]: 542
	[ALPHA]: 543
	[ALPHA]: 544
	[ALPHA]: 545
	[ALPHA]: 546
	[ALPHA]: 547
	[ALPHA]: 548
	[ALPHA]: 549
	[ALPHA]: 550
	[ALPHA]: 551
	[ALPHA]: 552
	[ALPHA]: 553
	[ALPHA]: 554
	[ALPHA]: 555
	[ALPHA]: 556
	[ALPHA]: 557
	[ALPHA]: 558
	[ALPHA]: 559
	[ALPHA]: 560
	[ALPHA]: 561
	[ALPHA]: 562
	[ALPHA]: 563
	[ALPHA]: 564
	[ALPHA]: 565
	[ALPHA]: 566
	[ALPHA]: 567
	[ALPHA]: 568
	[ALPHA]: 569
	[ALPHA]: 570
	[ALPHA]: 571
	[ALPHA]: 572
	[ALPHA]: 573
	[ALPHA]: 574
	[ALPHA]: 575
	[ALPHA]: 576
	[ALPHA]: 577
	[ALPHA]: 578
	[ALPHA]: 579
	[ALPHA]: 580
	[ALPHA]: 581
	[ALPHA]: 582
	[ALPHA]: 583
	[ALPHA]: 584
	[ALPHA]: 585
	[ALPHA]: 586
	[ALPHA]: 587
	[ALPHA]: 588
	[ALPHA]: 589
	[ALPHA]: 590
	[ALPHA]: 591
	[ALPHA]: 592
	[ALPHA]: 593
	[ALPHA]: 594
	[ALPHA]: 595
	[ALPHA]: 596
	[ALPHA]: 597
	[ALPHA]: 598
	[ALPHA]: 599
	[ALPHA]: 600
	[ALPHA]: 601
	[ALPHA]: 602
	[ALPHA]: 603
	[ALPHA]: 604
	[ALPHA]: 605
	[ALPHA]: 606
	[ALPHA]: 607
	[ALPHA]: 608
	[ALPHA]: 609
	[ALPHA]: 610
	[ALPHA]: 611
	[ALPHA]: 612
	[ALPHA]: 613
	[ALPHA]: 614
	[ALPHA]: 615
	[ALPHA]: 616
	[ALPHA]: 617
	[ALPHA]: 618
	[ALPHA]: 619
	[ALPHA]: 620
	[ALPHA]: 621
	[ALPHA]: 622
	[ALPHA]: 623
	[ALPHA]: 624
	[ALPHA]: 625
	[ALPHA]: 626
	[ALPHA]: 627
	[ALPHA]: 628
	[ALPHA]: 629
	[ALPHA]: 630
	[ALPHA]: 631
	[ALPHA]: 632
	[ALPHA]: 633
	[ALPHA]: 634
	[ALPHA]: 635
	[ALPHA]: 636
	[ALPHA]: 637
	[ALPHA]: 638
	[ALPHA]: 639
	[ALPHA]: 640
	[ALPHA]: 641
	[ALPHA]: 642
	[ALPHA]: 643
	[ALPHA]: 644
	[ALPHA]: 645
	[ALPHA]: 646
	[ALPHA]: 647
	[ALPHA]: 648
	[ALPHA]: 649
	[ALPHA]: 650
	[ALPHA]: 651
	[ALPHA]: 652
	[ALPHA]: 653
	[ALPHA]: 654
	[ALPHA]: 655
	[ALPHA]: 656
	[ALPHA]: 657
	[ALPHA]: 658
	[ALPHA]: 659
	[ALPHA]: 660
	[ALPHA]: 661
	[ALPHA]: 662
	[ALPHA]: 663
	[ALPHA]: 664
	[ALPHA]: 665
	[ALPHA]: 666
	[ALPHA]: 667
	[ALPHA]: 668
	[ALPHA]: 669
	[ALPHA]: 670
	[ALPHA]: 671
	[ALPHA]: 672
	[ALPHA]: 673
	[ALPHA]: 674
	[ALPHA]: 675
	[ALPHA]: 676
	[ALPHA]: 677
	[ALPHA]: 678
	[ALPHA]: 679
	[ALPHA]: 680
	[ALPHA]: 681
	[ALPHA]: 682
	[ALPHA]: 683
	[ALPHA]: 684
	[ALPHA]: 685
	[ALPHA]: 686
	[ALPHA]: 687
	[ALPHA]: 688
	[ALPHA]: 689
	[ALPHA]: 690
	[ALPHA]: 691
	[ALPHA]: 692
	[ALPHA]: 693
	[ALPHA]: 694
	[ALPHA]: 695
	[ALPHA]: 696
	[ALPHA]: 697
	[ALPHA]: 698
	[ALPHA]: 699
	[ALPHA]: 700
	[ALPHA]: 701
	[ALPHA]: 702
	[ALPHA]: 703
	[ALPHA]: 704
	[ALPHA]: 705
	[ALPHA]: 706
	[ALPHA]: 707
	[ALPHA]: 708
	[ALPHA]: 709
	[ALPHA]: 710
	[ALPHA]: 711
	[ALPHA]: 712
	[ALPHA]: 713
	[ALPHA]: 714
	[ALPHA]: 715
	[ALPHA]: 716
	[ALPHA]: 717
	[ALPHA]: 718
	[ALPHA]: 719
	[ALPHA]: 720
	[ALPHA]: 721
	[ALPHA]: 722
	[ALPHA]: 723
	[ALPHA]: 724
	[ALPHA]: 725
	[ALPHA]: 726
	[ALPHA]: 727
	[ALPHA]: 728
	[ALPHA]: 729
	[ALPHA]: 730
	[ALPHA]: 731
	[ALPHA]: 732
	[ALPHA]: 733
	[ALPHA]: 734
	[ALPHA]: 735
	[ALPHA]: 736
	[ALPHA]: 737
	[ALPHA]: 738
	[ALPHA]: 739
	[ALPHA]: 740
	[ALPHA]: 741
	[ALPHA]: 742
	[ALPHA]: 743
	[ALPHA]: 744
	[ALPHA]: 745
	[ALPHA]: 746
	[ALPHA]: 747
	[ALPHA]: 748
	[ALPHA]: 749
	[ALPHA]: 750
	[ALPHA]: 751
	[ALPHA]: 752
	[ALPHA]: 753
	[ALPHA]: 754
	[ALPHA]: 755
	[ALPHA]: 756
	[ALPHA]: 757
	[ALPHA]: 758
	[ALPHA]: 759
	[ALPHA]: 760
	[ALPHA]: 761
	[ALPHA]: 762
	[ALPHA]: 763
	[ALPHA]: 764
	[ALPHA]: 765
	[ALPHA]: 766
	[ALPHA]: 767
	[ALPHA]: 768
	[ALPHA]: 769
	[ALPHA]: 770
	[ALPHA]: 771
	[ALPHA]: 772
	[ALPHA]: 773
	[ALPHA]: 774
	[ALPHA]: 775
	[ALPHA]: 776
	[ALPHA]: 777
	[ALPHA]: 778
	[ALPHA]: 779
	[ALPHA]: 780
	[ALPHA]: 781
	[ALPHA]: 782
	[ALPHA]: 783
	[ALPHA]: 784
	[ALPHA]: 785
	[ALPHA]: 786
	[ALPHA]: 787
	[ALPHA]: 788
	[ALPHA]: 789
	[ALPHA]: 790
	[ALPHA]: 791
	[ALPHA]: 792
	[ALPHA]: 793
	[ALPHA]: 794
	[ALPHA]: 795
	[ALPHA]: 796
	[ALPHA]: 797
	[ALPHA]: 798
	[ALPHA]: 799
	[ALPHA]: 800
	[ALPHA]: 801
	[ALPHA]: 802
	[ALPHA]: 803
	[ALPHA]: 804
	[ALPHA]: 805
	[ALPHA]: 806
	[ALPHA]: 807
	[ALPHA]: 808
	[ALPHA]: 809
	[ALPHA]: 810
	[ALPHA]: 811
	[ALPHA]: 812
	[ALPHA]: 813
	[ALPHA]: 814
	[ALPHA]: 815
	[ALPHA]: 816
	[ALPHA]: 817
	[ALPHA]: 818
	[ALPHA]: 819
	[ALPHA]: 820
	[ALPHA]: 821
	[ALPHA]: 822
	[ALPHA]: 823
	[ALPHA]: 824
	[ALPHA]: 825
	[ALPHA]: 826
	[ALPHA]: 827
	[ALPHA]: 828
	[ALPHA]: 829
	[ALPHA]: 830
	[ALPHA]: 831
	[ALPHA]: 832
	[ALPHA]: 833
	[ALPHA]: 834
	[ALPHA]: 835
	[ALPHA]: 836
	[ALPHA]: 837
	[ALPHA]: 838
	[ALPHA]: 839
	[ALPHA]: 840
	[ALPHA]: 841
	[ALPHA]: 842
	[ALPHA]: 843
	[ALPHA]: 844
	[ALPHA]: 845
	[ALPHA]: 846
	[ALPHA]: 847
	[ALPHA]: 848
	[ALPHA]: 849
	[ALPHA]: 850
	[ALPHA]: 851
	[ALPHA]: 852
	[ALPHA]: 853
	[ALPHA]: 854
	[ALPHA]: 855
	[ALPHA]: 856
	[ALPHA]: 857
	[ALPHA]: 858
	[ALPHA]: 859
	[ALPHA]: 860
	[ALPHA]: 861
	[ALPHA]: 862
	[ALPHA]: 863
	[ALPHA]: 864
	[ALPHA]: 865
	[ALPHA]: 866
	[ALPHA]: 867
	[ALPHA]: 868
	[ALPHA]: 869
	[ALPHA]: 870
	[ALPHA]: 871
	[ALPHA]: 872
	[ALPHA]: 873
	[ALPHA]: 874
	[ALPHA]: 875
	[ALPHA]: 876
	[ALPHA]: 877
	[ALPHA]: 878
	[ALPHA]: 879
	[ALPHA]: 880
	[ALPHA]: 881
	[ALPHA]: 882
	[ALPHA]: 883
	[ALPHA]: 884
	[ALPHA]: 885
	[ALPHA]: 886
	[ALPHA]: 887
	[ALPHA]: 888
	[ALPHA]: 889
	[ALPHA]: 890
	[ALPHA]: 891
	[ALPHA]: 892
	[ALPHA]: 893
	[ALPHA]: 894
	[ALPHA]: 895
	[ALPHA]: 896
	[ALPHA]: 897
	[ALPHA]: 898
	[ALPHA]: 899
	[ALPHA]: 900
	[ALPHA]: 901
	[ALPHA]: 902
	[ALPHA]: 903
	[ALPHA]: 904
	[ALPHA]: 905
	[ALPHA]: 906
	[ALPHA]: 907
	[ALPHA]: 908
	[ALPHA]: 909
	[ALPHA]: 910
	[ALPHA]: 911
	[ALPHA]: 912
	[ALPHA]: 913
	[ALPHA]: 914
	[ALPHA]: 915
	[ALPHA]: 916
	[ALPHA]: 917
	[ALPHA]: 918
	[ALPHA]: 919
	[ALPHA]: 920
	[ALPHA]: 921
	[ALPHA]: 922
	[ALPHA]: 923
	[ALPHA]: 924
	[ALPHA]: 925
	[ALPHA]: 926
	[ALPHA]: 927
	[ALPHA]: 928
	[ALPHA]: 929
	[ALPHA]: 930
	[ALPHA]: 931
	[ALPHA]: 932
	[ALPHA]: 933
	[ALPHA]: 934
	[ALPHA]: 935
	[ALPHA]: 936
	[ALPHA]: 937
	[ALPHA]: 938
	[ALPHA]: 939
	[ALPHA]: 940
	[ALPHA]: 941
	[ALPHA]: 942
	[ALPHA]: 943
	[ALPHA]: 944
	[ALPHA]: 945
	[ALPHA]: 946
	[ALPHA]: 947
	[ALPHA]: 948
	[ALPHA]: 949
	[ALPHA]: 950
	[ALPHA]: 951
	[ALPHA]: 952
	[ALPHA]: 953
	[ALPHA]: 954
	[ALPHA]: 955
	[ALPHA]: 956
	[ALPHA]: 957
	[ALPHA]: 958
	[ALPHA]: 959
	[ALPHA]: 960
	[ALPHA]: 961
	[ALPHA]: 962
	[ALPHA]: 963
	[ALPHA]: 964
	[ALPHA]: 965
	[ALPHA]: 966
	[ALPHA]: 967
	[ALPHA]: 968
	[ALPHA]: 969
	[ALPHA]: 970
	[ALPHA]: 971
	[ALPHA]: 972
	[ALPHA]: 973
	[ALPHA]: 974
	[ALPHA]: 975
	[ALPHA]: 976
	[ALPHA]: 977
	[ALPHA]: 978
	[ALPHA]: 979
	[ALPHA]: 980
	[ALPHA]: 981
	[ALPHA]: 982
	[ALPHA]: 983
	[ALPHA]: 984
	[ALPHA]: 985
	[ALPHA]: 986
	[ALPHA]: 987
	[ALPHA]: 988
	[ALPHA]: 989
	[ALPHA]: 990
	[ALPHA]: 991
	[ALPHA]: 992
	[ALPHA]: 993
	[ALPHA]: 994
	[ALPHA]: 995
	[ALPHA]: 996
	[ALPHA]: 997
	[ALPHA]: 998
	[ALPHA]: 999
[Fold]: 1
	[ALPHA]: 0
	[ALPHA]: 1
	[ALPHA]: 2
	[ALPHA]: 3
	[ALPHA]: 4
	[ALPHA]: 5
	[ALPHA]: 6
	[ALPHA]: 7
	[ALPHA]: 8
	[ALPHA]: 9
	[ALPHA]: 10
	[ALPHA]: 11
	[ALPHA]: 12
	[ALPHA]: 13
	[ALPHA]: 14
	[ALPHA]: 15
	[ALPHA]: 16
	[ALPHA]: 17
	[ALPHA]: 18
	[ALPHA]: 19
	[ALPHA]: 20
	[ALPHA]: 21
	[ALPHA]: 22
	[ALPHA]: 23
	[ALPHA]: 24
	[ALPHA]: 25
	[ALPHA]: 26
	[ALPHA]: 27
	[ALPHA]: 28
	[ALPHA]: 29
	[ALPHA]: 30
	[ALPHA]: 31
	[ALPHA]: 32
	[ALPHA]: 33
	[ALPHA]: 34
	[ALPHA]: 35
	[ALPHA]: 36
	[ALPHA]: 37
	[ALPHA]: 38
	[ALPHA]: 39
	[ALPHA]: 40
	[ALPHA]: 41
	[ALPHA]: 42
	[ALPHA]: 43
	[ALPHA]: 44
	[ALPHA]: 45
	[ALPHA]: 46
	[ALPHA]: 47
	[ALPHA]: 48
	[ALPHA]: 49
	[ALPHA]: 50
	[ALPHA]: 51
	[ALPHA]: 52
	[ALPHA]: 53
	[ALPHA]: 54
	[ALPHA]: 55
	[ALPHA]: 56
	[ALPHA]: 57
	[ALPHA]: 58
	[ALPHA]: 59
	[ALPHA]: 60
	[ALPHA]: 61
	[ALPHA]: 62
	[ALPHA]: 63
	[ALPHA]: 64
	[ALPHA]: 65
	[ALPHA]: 66
	[ALPHA]: 67
	[ALPHA]: 68
	[ALPHA]: 69
	[ALPHA]: 70
	[ALPHA]: 71
	[ALPHA]: 72
	[ALPHA]: 73
	[ALPHA]: 74
	[ALPHA]: 75
	[ALPHA]: 76
	[ALPHA]: 77
	[ALPHA]: 78
	[ALPHA]: 79
	[ALPHA]: 80
	[ALPHA]: 81
	[ALPHA]: 82
	[ALPHA]: 83
	[ALPHA]: 84
	[ALPHA]: 85
	[ALPHA]: 86
	[ALPHA]: 87
	[ALPHA]: 88
	[ALPHA]: 89
	[ALPHA]: 90
	[ALPHA]: 91
	[ALPHA]: 92
	[ALPHA]: 93
	[ALPHA]: 94
	[ALPHA]: 95
	[ALPHA]: 96
	[ALPHA]: 97
	[ALPHA]: 98
	[ALPHA]: 99
	[ALPHA]: 100
	[ALPHA]: 101
	[ALPHA]: 102
	[ALPHA]: 103
	[ALPHA]: 104
	[ALPHA]: 105
	[ALPHA]: 106
	[ALPHA]: 107
	[ALPHA]: 108
	[ALPHA]: 109
	[ALPHA]: 110
	[ALPHA]: 111
	[ALPHA]: 112
	[ALPHA]: 113
	[ALPHA]: 114
	[ALPHA]: 115
	[ALPHA]: 116
	[ALPHA]: 117
	[ALPHA]: 118
	[ALPHA]: 119
	[ALPHA]: 120
	[ALPHA]: 121
	[ALPHA]: 122
	[ALPHA]: 123
	[ALPHA]: 124
	[ALPHA]: 125
	[ALPHA]: 126
	[ALPHA]: 127
	[ALPHA]: 128
	[ALPHA]: 129
	[ALPHA]: 130
	[ALPHA]: 131
	[ALPHA]: 132
	[ALPHA]: 133
	[ALPHA]: 134
	[ALPHA]: 135
	[ALPHA]: 136
	[ALPHA]: 137
	[ALPHA]: 138
	[ALPHA]: 139
	[ALPHA]: 140
	[ALPHA]: 141
	[ALPHA]: 142
	[ALPHA]: 143
	[ALPHA]: 144
	[ALPHA]: 145
	[ALPHA]: 146
	[ALPHA]: 147
	[ALPHA]: 148
	[ALPHA]: 149
	[ALPHA]: 150
	[ALPHA]: 151
	[ALPHA]: 152
	[ALPHA]: 153
	[ALPHA]: 154
	[ALPHA]: 155
	[ALPHA]: 156
	[ALPHA]: 157
	[ALPHA]: 158
	[ALPHA]: 159
	[ALPHA]: 160
	[ALPHA]: 161
	[ALPHA]: 162
	[ALPHA]: 163
	[ALPHA]: 164
	[ALPHA]: 165
	[ALPHA]: 166
	[ALPHA]: 167
	[ALPHA]: 168
	[ALPHA]: 169
	[ALPHA]: 170
	[ALPHA]: 171
	[ALPHA]: 172
	[ALPHA]: 173
	[ALPHA]: 174
	[ALPHA]: 175
	[ALPHA]: 176
	[ALPHA]: 177
	[ALPHA]: 178
	[ALPHA]: 179
	[ALPHA]: 180
	[ALPHA]: 181
	[ALPHA]: 182
	[ALPHA]: 183
	[ALPHA]: 184
	[ALPHA]: 185
	[ALPHA]: 186
	[ALPHA]: 187
	[ALPHA]: 188
	[ALPHA]: 189
	[ALPHA]: 190
	[ALPHA]: 191
	[ALPHA]: 192
	[ALPHA]: 193
	[ALPHA]: 194
	[ALPHA]: 195
	[ALPHA]: 196
	[ALPHA]: 197
	[ALPHA]: 198
	[ALPHA]: 199
	[ALPHA]: 200
	[ALPHA]: 201
	[ALPHA]: 202
	[ALPHA]: 203
	[ALPHA]: 204
	[ALPHA]: 205
	[ALPHA]: 206
	[ALPHA]: 207
	[ALPHA]: 208
	[ALPHA]: 209
	[ALPHA]: 210
	[ALPHA]: 211
	[ALPHA]: 212
	[ALPHA]: 213
	[ALPHA]: 214
	[ALPHA]: 215
	[ALPHA]: 216
	[ALPHA]: 217
	[ALPHA]: 218
	[ALPHA]: 219
	[ALPHA]: 220
	[ALPHA]: 221
	[ALPHA]: 222
	[ALPHA]: 223
	[ALPHA]: 224
	[ALPHA]: 225
	[ALPHA]: 226
	[ALPHA]: 227
	[ALPHA]: 228
	[ALPHA]: 229
	[ALPHA]: 230
	[ALPHA]: 231
	[ALPHA]: 232
	[ALPHA]: 233
	[ALPHA]: 234
	[ALPHA]: 235
	[ALPHA]: 236
	[ALPHA]: 237
	[ALPHA]: 238
	[ALPHA]: 239
	[ALPHA]: 240
	[ALPHA]: 241
	[ALPHA]: 242
	[ALPHA]: 243
	[ALPHA]: 244
	[ALPHA]: 245
	[ALPHA]: 246
	[ALPHA]: 247
	[ALPHA]: 248
	[ALPHA]: 249
	[ALPHA]: 250
	[ALPHA]: 251
	[ALPHA]: 252
	[ALPHA]: 253
	[ALPHA]: 254
	[ALPHA]: 255
	[ALPHA]: 256
	[ALPHA]: 257
	[ALPHA]: 258
	[ALPHA]: 259
	[ALPHA]: 260
	[ALPHA]: 261
	[ALPHA]: 262
	[ALPHA]: 263
	[ALPHA]: 264
	[ALPHA]: 265
	[ALPHA]: 266
	[ALPHA]: 267
	[ALPHA]: 268
	[ALPHA]: 269
	[ALPHA]: 270
	[ALPHA]: 271
	[ALPHA]: 272
	[ALPHA]: 273
	[ALPHA]: 274
	[ALPHA]: 275
	[ALPHA]: 276
	[ALPHA]: 277
	[ALPHA]: 278
	[ALPHA]: 279
	[ALPHA]: 280
	[ALPHA]: 281
	[ALPHA]: 282
	[ALPHA]: 283
	[ALPHA]: 284
	[ALPHA]: 285
	[ALPHA]: 286
	[ALPHA]: 287
	[ALPHA]: 288
	[ALPHA]: 289
	[ALPHA]: 290
	[ALPHA]: 291
	[ALPHA]: 292
	[ALPHA]: 293
	[ALPHA]: 294
	[ALPHA]: 295
	[ALPHA]: 296
	[ALPHA]: 297
	[ALPHA]: 298
	[ALPHA]: 299
	[ALPHA]: 300
	[ALPHA]: 301
	[ALPHA]: 302
	[ALPHA]: 303
	[ALPHA]: 304
	[ALPHA]: 305
	[ALPHA]: 306
	[ALPHA]: 307
	[ALPHA]: 308
	[ALPHA]: 309
	[ALPHA]: 310
	[ALPHA]: 311
	[ALPHA]: 312
	[ALPHA]: 313
	[ALPHA]: 314
	[ALPHA]: 315
	[ALPHA]: 316
	[ALPHA]: 317
	[ALPHA]: 318
	[ALPHA]: 319
	[ALPHA]: 320
	[ALPHA]: 321
	[ALPHA]: 322
	[ALPHA]: 323
	[ALPHA]: 324
	[ALPHA]: 325
	[ALPHA]: 326
	[ALPHA]: 327
	[ALPHA]: 328
	[ALPHA]: 329
	[ALPHA]: 330
	[ALPHA]: 331
	[ALPHA]: 332
	[ALPHA]: 333
	[ALPHA]: 334
	[ALPHA]: 335
	[ALPHA]: 336
	[ALPHA]: 337
	[ALPHA]: 338
	[ALPHA]: 339
	[ALPHA]: 340
	[ALPHA]: 341
	[ALPHA]: 342
	[ALPHA]: 343
	[ALPHA]: 344
	[ALPHA]: 345
	[ALPHA]: 346
	[ALPHA]: 347
	[ALPHA]: 348
	[ALPHA]: 349
	[ALPHA]: 350
	[ALPHA]: 351
	[ALPHA]: 352
	[ALPHA]: 353
	[ALPHA]: 354
	[ALPHA]: 355
	[ALPHA]: 356
	[ALPHA]: 357
	[ALPHA]: 358
	[ALPHA]: 359
	[ALPHA]: 360
	[ALPHA]: 361
	[ALPHA]: 362
	[ALPHA]: 363
	[ALPHA]: 364
	[ALPHA]: 365
	[ALPHA]: 366
	[ALPHA]: 367
	[ALPHA]: 368
	[ALPHA]: 369
	[ALPHA]: 370
	[ALPHA]: 371
	[ALPHA]: 372
	[ALPHA]: 373
	[ALPHA]: 374
	[ALPHA]: 375
	[ALPHA]: 376
	[ALPHA]: 377
	[ALPHA]: 378
	[ALPHA]: 379
	[ALPHA]: 380
	[ALPHA]: 381
	[ALPHA]: 382
	[ALPHA]: 383
	[ALPHA]: 384
	[ALPHA]: 385
	[ALPHA]: 386
	[ALPHA]: 387
	[ALPHA]: 388
	[ALPHA]: 389
	[ALPHA]: 390
	[ALPHA]: 391
	[ALPHA]: 392
	[ALPHA]: 393
	[ALPHA]: 394
	[ALPHA]: 395
	[ALPHA]: 396
	[ALPHA]: 397
	[ALPHA]: 398
	[ALPHA]: 399
	[ALPHA]: 400
	[ALPHA]: 401
	[ALPHA]: 402
	[ALPHA]: 403
	[ALPHA]: 404
	[ALPHA]: 405
	[ALPHA]: 406
	[ALPHA]: 407
	[ALPHA]: 408
	[ALPHA]: 409
	[ALPHA]: 410
	[ALPHA]: 411
	[ALPHA]: 412
	[ALPHA]: 413
	[ALPHA]: 414
	[ALPHA]: 415
	[ALPHA]: 416
	[ALPHA]: 417
	[ALPHA]: 418
	[ALPHA]: 419
	[ALPHA]: 420
	[ALPHA]: 421
	[ALPHA]: 422
	[ALPHA]: 423
	[ALPHA]: 424
	[ALPHA]: 425
	[ALPHA]: 426
	[ALPHA]: 427
	[ALPHA]: 428
	[ALPHA]: 429
	[ALPHA]: 430
	[ALPHA]: 431
	[ALPHA]: 432
	[ALPHA]: 433
	[ALPHA]: 434
	[ALPHA]: 435
	[ALPHA]: 436
	[ALPHA]: 437
	[ALPHA]: 438
	[ALPHA]: 439
	[ALPHA]: 440
	[ALPHA]: 441

In [45]:
print(f"Best lambda : {results['best_alpha']:.4f}")
print(f"Best CV MSE : {results['best_cv_mse']:.2f}")
print(f"Best CV RMSE: {results['best_cv_rmse']:.2f}")

Best lambda : 0.0041
Best CV MSE : 294802.85
Best CV RMSE: 542.96

# Fitting Best Model

In [46]:
from scripts.find_alpha_ridge import fit_final_ridge

In [47]:
model, scaler = fit_final_ridge(X, y, alpha=results["best_alpha"])

In [48]:
df_test = pd.read_csv(f"data-01-processed/ridge_regression_test.csv", index_col=[0])

df_test_with_date = pd.read_csv(f"data-00-raw/bike_test.csv", index_col=[0])

In [49]:
preds = model.predict(scaler.transform(df_test.to_numpy()))

# Submission Generator

In [50]:
from scripts.save_submission import save_submission_csv

In [51]:
df_submission = pd.DataFrame({"date": df_test_with_date["date"], "pred": preds})

df_submission

           date         pred
1    2023-01-01  2296.488252
2    2023-01-02  2036.206043
3    2023-01-03  1075.455903
4    2023-01-04   791.471213
5    2023-01-05  2198.460157
..          ...          ...
361  2023-12-27   329.280939
362  2023-12-28  1743.230509
363  2023-12-29  2309.075091
364  2023-12-30  2076.948323
365  2023-12-31  2227.704039

[365 rows x 2 columns]

In [52]:
save_submission_csv(df_submission)