In [1]:
import pandas as pd
import numpy as np


RANDOM_STATE = 42

In [2]:
df_train_raw = pd.read_csv(f"data-00-raw/bike_train.csv", index_col=[0], parse_dates=["date"])

df_test_raw = pd.read_csv(f"data-00-raw/bike_test.csv", index_col=[0], parse_dates=["date"])

df_train_raw

          date  wcond  temp  atemp    hum   wind  count
1   2022-01-01      2   9.1   13.2  79.78  10.43    982
2   2022-01-02      2   9.9   12.7  68.91  16.16    797
3   2022-01-03      1   3.1    4.5  43.29  16.14   1351
4   2022-01-04      1   3.2    5.6  58.45  10.42   1559
5   2022-01-05      1   4.3    6.5  43.26  12.15   1597
..         ...    ...   ...    ...    ...    ...    ...
361 2022-12-27      2   8.3   11.4  75.49  12.25   1161
362 2022-12-28      1   7.3    9.0  49.89  19.11   2301
363 2022-12-29      1   5.2    8.2  56.84   7.76   2421
364 2022-12-30      1   7.8   10.9  63.03   8.73   2995
365 2022-12-31      1  11.8   15.7  60.97  14.31   2485

[365 rows x 7 columns]

In [3]:
from scripts.add_features import add_calendar_features_lgb, add_weather_features_lgb, get_lgb_features_cols

In [4]:
df_train = add_calendar_features_lgb(add_weather_features_lgb(df_train_raw))

df_test = add_calendar_features_lgb(add_weather_features_lgb(df_test_raw))

df_train

,date,wcond,temp,atemp,hum,wind,count,temp_sq,hum_sq,wind_sq,...,dayofweek,weekend,dayofyear,quarter,sin_doy_1,cos_doy_1,sin_doy_2,cos_doy_2,sin_doy_3,cos_doy_3
1,2022-01-01,2,9.1,13.2,79.78,10.43,982,82.81,6364.8484,108.7849,...,5,1,1,1,1.721336e-02,0.999852,3.442161e-02,0.999407,5.161967e-02,0.998667
2,2022-01-02,2,9.9,12.7,68.91,16.16,797,98.01,4748.5881,261.1456,...,6,1,2,1,3.442161e-02,0.999407,6.880243e-02,0.997630,1.031017e-01,0.994671
3,2022-01-03,1,3.1,4.5,43.29,16.14,1351,9.61,1874.0241,260.4996,...,0,0,3,1,5.161967e-02,0.998667,1.031017e-01,0.994671,1.543088e-01,0.988023
4,2022-01-04,1,3.2,5.6,58.45,10.42,1559,10.24,3416.4025,108.5764,...,1,0,4,1,6.880243e-02,0.997630,1.372788e-01,0.990532,2.051045e-01,0.978740
5,2022-01-05,1,4.3,6.5,43.26,12.15,1597,18.49,1871.4276,147.6225,...,2,0,5,1,8.596480e-02,0.996298,1.712931e-01,0.985220,2.553533e-01,0.966848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2022-12-27,2,8.3,11.4,75.49,12.25,1161,68.89,5698.7401,150.0625,...,1,0,361,4,-6.880243e-02,0.997630,-1.372788e-01,0.990532,-2.051045e-01,0.978740
362,2022-12-28,1,7.3,9.0,49.89,19.11,2301,53.29,2489.0121,365.1921,...,2,0,362,4,-5.161967e-02,0.998667,-1.031017e-01,0.994671,-1.543088e-01,0.988023
363,2022-12-29,1,5.2,8.2,56.84,7.76,2421,27.04,3230.7856,60.2176,...,3,0,363,4,-3.442161e-02,0.999407,-6.880243e-02,0.997630,-1.031017e-01,0.994671
364,2022-12-30,1,7.8,10.9,63.03,8.73,2995,60.84,3972.7809,76.2129,...,4,0,364,4,-1.721336e-02,0.999852,-3.442161e-02,0.999407,-5.161967e-02,0.998667
365,2022-12-31,1,11.8,15.7,60.97,14.31,2485,139.24,3717.3409,204.7761,...,5,1,365,4,6.432491e-16,1.000000,1.286498e-15,1.000000,-7.347881e-16,1.000000

# Cross Validation

### Preparing Data

In [9]:
y = df_train["count"].to_numpy()

In [10]:
df_train_X = df_train[get_lgb_features_cols()].copy()

df_test_X = df_test[get_lgb_features_cols()].copy()

df_train_X

,temp,atemp,hum,wind,wcond,temp_sq,hum_sq,wind_sq,temp_x_hum,temp_x_wind,...,dayofweek,weekend,dayofyear,quarter,sin_doy_1,cos_doy_1,sin_doy_2,cos_doy_2,sin_doy_3,cos_doy_3
1,9.1,13.2,79.78,10.43,2,82.81,6364.8484,108.7849,725.998,94.913,...,5,1,1,1,1.721336e-02,0.999852,3.442161e-02,0.999407,5.161967e-02,0.998667
2,9.9,12.7,68.91,16.16,2,98.01,4748.5881,261.1456,682.209,159.984,...,6,1,2,1,3.442161e-02,0.999407,6.880243e-02,0.997630,1.031017e-01,0.994671
3,3.1,4.5,43.29,16.14,1,9.61,1874.0241,260.4996,134.199,50.034,...,0,0,3,1,5.161967e-02,0.998667,1.031017e-01,0.994671,1.543088e-01,0.988023
4,3.2,5.6,58.45,10.42,1,10.24,3416.4025,108.5764,187.040,33.344,...,1,0,4,1,6.880243e-02,0.997630,1.372788e-01,0.990532,2.051045e-01,0.978740
5,4.3,6.5,43.26,12.15,1,18.49,1871.4276,147.6225,186.018,52.245,...,2,0,5,1,8.596480e-02,0.996298,1.712931e-01,0.985220,2.553533e-01,0.966848
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,8.3,11.4,75.49,12.25,2,68.89,5698.7401,150.0625,626.567,101.675,...,1,0,361,4,-6.880243e-02,0.997630,-1.372788e-01,0.990532,-2.051045e-01,0.978740
362,7.3,9.0,49.89,19.11,1,53.29,2489.0121,365.1921,364.197,139.503,...,2,0,362,4,-5.161967e-02,0.998667,-1.031017e-01,0.994671,-1.543088e-01,0.988023
363,5.2,8.2,56.84,7.76,1,27.04,3230.7856,60.2176,295.568,40.352,...,3,0,363,4,-3.442161e-02,0.999407,-6.880243e-02,0.997630,-1.031017e-01,0.994671
364,7.8,10.9,63.03,8.73,1,60.84,3972.7809,76.2129,491.634,68.094,...,4,0,364,4,-1.721336e-02,0.999852,-3.442161e-02,0.999407,-5.161967e-02,0.998667
365,11.8,15.7,60.97,14.31,1,139.24,3717.3409,204.7761,719.446,168.858,...,5,1,365,4,6.432491e-16,1.000000,1.286498e-15,1.000000,-7.347881e-16,1.000000

### Selecting Parameters

In [15]:
from sklearn.model_selection import KFold
import optuna
from scripts.find_solve_lightgbm import make_objective, fit_final_lgbm

In [12]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)

N_TRIALS = 100

study = optuna.create_study(direction="minimize")

study.optimize(make_objective(df_test_X, y, kf), n_trials=N_TRIALS, show_progress_bar=True)

best_params = study.best_params
best_mse = study.best_value
best_rmse = np.sqrt(best_mse)

[I 2026-06-01 14:04:04,229] A new study created in memory with name: no-name-1dbf4058-a551-4f5b-8840-440b80e50137

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-06-01 14:04:04,348] Trial 0 finished with value: 551947.7897685936 and parameters: {'n_estimators': 551, 'learning_rate': 0.013742977871169595, 'num_leaves': 104, 'max_depth': 9, 'min_child_samples': 46, 'subsample': 0.7011904828235671, 'colsample_bytree': 0.8587269509691378, 'reg_alpha': 2.3529315604724275, 'reg_lambda': 0.018418881227566488}. Best is trial 0 with value: 551947.7897685936.
[I 2026-06-01 14:04:04,679] Trial 1 finished with value: 667556.1935041352 and parameters: {'n_estimators': 895, 'learning_rate': 0.0014544742378309878, 'num_leaves': 82, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6374527169776074, 'colsample_bytree': 0.6963006792232392, 'reg_alpha': 0.021971201890585604, 'reg_lambda': 5.921092131773981}. Best is trial 0 with value: 551947.7897685936.
[I 2026-06-01 14:04:04,714] Trial 2 finished with value: 554068.3337419977 and parameters: {'n_estimators': 487, 'learning_rate': 0.13464909074483206, 'num_leaves': 46, 'max_depth': 4, 'min_child_samples': 44, 'subsample': 0.8254266803665161, 'colsample_bytree': 0.7123301503419582, 'reg_alpha': 0.005997124634440756, 'reg_lambda': 0.0011946294009801126}. Best is trial 0 with value: 551947.7897685936.
[I 2026-06-01 14:04:04,765] Trial 3 finished with value: 550010.693310172 and parameters: {'n_estimators': 877, 'learning_rate': 0.05290175356502674, 'num_leaves': 27, 'max_depth': 10, 'min_child_samples': 48, 'subsample': 0.6578426582421022, 'colsample_bytree': 0.5564110462764393, 'reg_alpha': 0.000405072494940809, 'reg_lambda': 0.0001622755064497526}. Best is trial 3 with value: 550010.693310172.
[I 2026-06-01 14:04:04,802] Trial 4 finished with value: 555985.7493919951 and parameters: {'n_estimators': 262, 'learning_rate': 0.18991508934034645, 'num_leaves': 111, 'max_depth': 10, 'min_child_samples': 33, 'subsample': 0.5119647141500803, 'colsample_bytree': 0.6678703521486137, 'reg_alpha': 1.695843919978304, 'reg_lambda': 0.00031804968175680877}. Best is trial 3 with value: 550010.693310172.
[I 2026-06-01 14:04:04,961] Trial 5 finished with value: 975253.0530099847 and parameters: {'n_estimators': 275, 'learning_rate': 0.0020292529265954727, 'num_leaves': 27, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.6834452564626305, 'colsample_bytree': 0.8807035342823077, 'reg_alpha': 0.0001408813553218504, 'reg_lambda': 0.0009213742290687266}. Best is trial 3 with value: 550010.693310172.
[I 2026-06-01 14:04:05,008] Trial 6 finished with value: 552669.9360923672 and parameters: {'n_estimators': 748, 'learning_rate': 0.051872796424699046, 'num_leaves': 73, 'max_depth': 8, 'min_child_samples': 39, 'subsample': 0.8407036849696081, 'colsample_bytree': 0.5010423541926514, 'reg_alpha': 0.00047929626730517695, 'reg_lambda': 0.00010433493814159581}. Best is trial 3 with value: 550010.693310172.
[I 2026-06-01 14:04:05,101] Trial 7 finished with value: 532559.4056734454 and parameters: {'n_estimators': 317, 'learning_rate': 0.021125849878508896, 'num_leaves': 41, 'max_depth': 4, 'min_child_samples': 6, 'subsample': 0.6477656243606651, 'colsample_bytree': 0.6500446266625657, 'reg_alpha': 0.0001087625203139241, 'reg_lambda': 0.2514242302840461}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:05,142] Trial 8 finished with value: 552190.6616092882 and parameters: {'n_estimators': 560, 'learning_rate': 0.05668131118157392, 'num_leaves': 109, 'max_depth': 5, 'min_child_samples': 37, 'subsample': 0.811608657871363, 'colsample_bytree': 0.723199382923364, 'reg_alpha': 0.00014692565580528896, 'reg_lambda': 0.00021000041199431075}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:05,281] Trial 9 finished with value: 806858.0079915058 and parameters: {'n_estimators': 433, 'learning_rate': 0.00192860388254755, 'num_leaves': 25, 'max_depth': 6, 'min_child_samples': 23, 'subsample': 0.7040969648219977, 'colsample_bytree': 0.6141430938949577, 'reg_alpha': 0.0015294458531709514, 'reg_lambda': 0.776809746587707}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:05,335] Trial 10 finished with value: 725680.8956049604 and parameters: {'n_estimators': 136, 'learning_rate': 0.007223127173081076, 'num_leaves': 52, 'max_depth': 3, 'min_child_samples': 19, 'subsample': 0.5130285762030189, 'colsample_bytree': 0.9996032632238567, 'reg_alpha': 0.2724867570372388, 'reg_lambda': 0.09130365719761592}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:05,394] Trial 11 finished with value: 550839.0086189294 and parameters: {'n_estimators': 995, 'learning_rate': 0.03514257096956182, 'num_leaves': 47, 'max_depth': 7, 'min_child_samples': 50, 'subsample': 0.9621406677949768, 'colsample_bytree': 0.5431224891480787, 'reg_alpha': 0.001460100660588759, 'reg_lambda': 0.016113395544411723}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:05,516] Trial 12 finished with value: 537396.4286609835 and parameters: {'n_estimators': 714, 'learning_rate': 0.008363450236142878, 'num_leaves': 16, 'max_depth': 3, 'min_child_samples': 17, 'subsample': 0.6015646109797959, 'colsample_bytree': 0.6057291934521462, 'reg_alpha': 0.0001089803367039685, 'reg_lambda': 0.13894602127858807}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:05,643] Trial 13 finished with value: 539112.4659082026 and parameters: {'n_estimators': 719, 'learning_rate': 0.006411186247127932, 'num_leaves': 15, 'max_depth': 3, 'min_child_samples': 15, 'subsample': 0.5907931488199865, 'colsample_bytree': 0.6231918194157269, 'reg_alpha': 0.09842264882776099, 'reg_lambda': 0.191756083592765}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:05,762] Trial 14 finished with value: 547012.4277074378 and parameters: {'n_estimators': 670, 'learning_rate': 0.01510876408113545, 'num_leaves': 61, 'max_depth': 4, 'min_child_samples': 5, 'subsample': 0.5619618794370419, 'colsample_bytree': 0.805744331257572, 'reg_alpha': 0.007450460589175712, 'reg_lambda': 0.6114564472793627}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:05,856] Trial 15 finished with value: 594883.3609912298 and parameters: {'n_estimators': 344, 'learning_rate': 0.005558145094735975, 'num_leaves': 37, 'max_depth': 4, 'min_child_samples': 28, 'subsample': 0.7574517608891053, 'colsample_bytree': 0.6208775961356696, 'reg_alpha': 0.0001021371968441928, 'reg_lambda': 8.5982728604202}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:06,018] Trial 16 finished with value: 542865.1320239406 and parameters: {'n_estimators': 638, 'learning_rate': 0.0038192242352739474, 'num_leaves': 17, 'max_depth': 3, 'min_child_samples': 14, 'subsample': 0.5968511316872684, 'colsample_bytree': 0.7815944735594929, 'reg_alpha': 9.715263153737576, 'reg_lambda': 0.004274156080001674}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:06,077] Trial 17 finished with value: 544105.0989111852 and parameters: {'n_estimators': 123, 'learning_rate': 0.025021182704632113, 'num_leaves': 37, 'max_depth': 5, 'min_child_samples': 21, 'subsample': 0.7633261212989353, 'colsample_bytree': 0.5880045357127219, 'reg_alpha': 0.0012149091390735365, 'reg_lambda': 0.8478819436923953}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:06,276] Trial 18 finished with value: 557600.2866500223 and parameters: {'n_estimators': 387, 'learning_rate': 0.015083911450182905, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.9966400087569497, 'colsample_bytree': 0.6549420129315122, 'reg_alpha': 0.006454059866663824, 'reg_lambda': 0.08444464988558913}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:06,334] Trial 19 finished with value: 542969.372656646 and parameters: {'n_estimators': 818, 'learning_rate': 0.09839113884315782, 'num_leaves': 61, 'max_depth': 4, 'min_child_samples': 16, 'subsample': 0.6178580015146838, 'colsample_bytree': 0.7622805394102271, 'reg_alpha': 0.00047464582087306006, 'reg_lambda': 2.238835079665761}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:06,395] Trial 20 finished with value: 564600.5193537453 and parameters: {'n_estimators': 215, 'learning_rate': 0.009519062272920766, 'num_leaves': 127, 'max_depth': 3, 'min_child_samples': 27, 'subsample': 0.5557375482051717, 'colsample_bytree': 0.5033954773955511, 'reg_alpha': 0.028567076945804407, 'reg_lambda': 0.14097504584564638}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:06,564] Trial 21 finished with value: 547682.4659799467 and parameters: {'n_estimators': 682, 'learning_rate': 0.0035051574646591263, 'num_leaves': 15, 'max_depth': 3, 'min_child_samples': 12, 'subsample': 0.5781696637055884, 'colsample_bytree': 0.6302604675774112, 'reg_alpha': 0.1400800222650473, 'reg_lambda': 0.2472408560789756}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:06,673] Trial 22 finished with value: 537296.9684284577 and parameters: {'n_estimators': 619, 'learning_rate': 0.009195328728522165, 'num_leaves': 33, 'max_depth': 3, 'min_child_samples': 17, 'subsample': 0.6337811600007499, 'colsample_bytree': 0.6657329728503042, 'reg_alpha': 0.17125351270122535, 'reg_lambda': 0.039715815749081014}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:06,743] Trial 23 finished with value: 542872.4248727544 and parameters: {'n_estimators': 602, 'learning_rate': 0.026062966265481827, 'num_leaves': 37, 'max_depth': 4, 'min_child_samples': 26, 'subsample': 0.6539683570451308, 'colsample_bytree': 0.5708959598481199, 'reg_alpha': 0.5126490137340659, 'reg_lambda': 0.03235722061893266}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:06,863] Trial 24 finished with value: 549949.2569966998 and parameters: {'n_estimators': 466, 'learning_rate': 0.010480792805194945, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 18, 'subsample': 0.7293574074952244, 'colsample_bytree': 0.6704046698309131, 'reg_alpha': 0.05765378116368725, 'reg_lambda': 0.03823827375417923}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:07,057] Trial 25 finished with value: 536166.0829294778 and parameters: {'n_estimators': 753, 'learning_rate': 0.0033335234595877547, 'num_leaves': 57, 'max_depth': 3, 'min_child_samples': 8, 'subsample': 0.5420652878415853, 'colsample_bytree': 0.736079654502885, 'reg_alpha': 0.5560191782747003, 'reg_lambda': 0.007075140503879367}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:07,347] Trial 26 finished with value: 547712.5385584426 and parameters: {'n_estimators': 833, 'learning_rate': 0.0034050637593061152, 'num_leaves': 61, 'max_depth': 4, 'min_child_samples': 8, 'subsample': 0.5386027832049717, 'colsample_bytree': 0.8265952862672019, 'reg_alpha': 0.8937119101207998, 'reg_lambda': 0.0038952935731453083}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:07,766] Trial 27 finished with value: 764996.251054362 and parameters: {'n_estimators': 795, 'learning_rate': 0.0011163049867570457, 'num_leaves': 55, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.6617291045123198, 'colsample_bytree': 0.7389023479267635, 'reg_alpha': 5.978495434958256, 'reg_lambda': 0.005166317155781828}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:07,893] Trial 28 finished with value: 542380.100067086 and parameters: {'n_estimators': 507, 'learning_rate': 0.004855581795942789, 'num_leaves': 70, 'max_depth': 3, 'min_child_samples': 12, 'subsample': 0.6209897084851278, 'colsample_bytree': 0.6955905844058912, 'reg_alpha': 0.634728671474735, 'reg_lambda': 0.010982711692311133}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:08,026] Trial 29 finished with value: 555917.5882678594 and parameters: {'n_estimators': 595, 'learning_rate': 0.021009225628944146, 'num_leaves': 43, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.705535178093578, 'colsample_bytree': 0.8938244712054815, 'reg_alpha': 3.3918371655631634, 'reg_lambda': 0.046669484730084365}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:08,256] Trial 30 finished with value: 747945.6569935505 and parameters: {'n_estimators': 359, 'learning_rate': 0.002537414080920531, 'num_leaves': 67, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.5484140643033175, 'colsample_bytree': 0.9402728412624746, 'reg_alpha': 0.23106465792761022, 'reg_lambda': 0.008128548583118395}. Best is trial 7 with value: 532559.4056734454.
[I 2026-06-01 14:04:08,355] Trial 31 finished with value: 530989.4579723611 and parameters: {'n_estimators': 736, 'learning_rate': 0.009162836541963558, 'num_leaves': 23, 'max_depth': 3, 'min_child_samples': 22, 'subsample': 0.6100336085467319, 'colsample_bytree': 0.6493646969076793, 'reg_alpha': 1.780029999981648, 'reg_lambda': 0.513709793232876}. Best is trial 31 with value: 530989.4579723611.
[I 2026-06-01 14:04:08,470] Trial 32 finished with value: 539231.6585734925 and parameters: {'n_estimators': 956, 'learning_rate': 0.010963141239734533, 'num_leaves': 43, 'max_depth': 4, 'min_child_samples': 20, 'subsample': 0.5000179695444764, 'colsample_bytree': 0.6832548010801739, 'reg_alpha': 1.2594012164740032, 'reg_lambda': 2.627375172528655}. Best is trial 31 with value: 530989.4579723611.
[I 2026-06-01 14:04:08,553] Trial 33 finished with value: 531987.3785754568 and parameters: {'n_estimators': 780, 'learning_rate': 0.012713788248682549, 'num_leaves': 34, 'max_depth': 3, 'min_child_samples': 23, 'subsample': 0.6310775191781307, 'colsample_bytree': 0.6495781557544923, 'reg_alpha': 0.3517071357967698, 'reg_lambda': 0.39982191612689627}. Best is trial 31 with value: 530989.4579723611.
[I 2026-06-01 14:04:08,609] Trial 34 finished with value: 539157.2560167582 and parameters: {'n_estimators': 908, 'learning_rate': 0.03462340968090451, 'num_leaves': 53, 'max_depth': 4, 'min_child_samples': 30, 'subsample': 0.6644929224443074, 'colsample_bytree': 0.7219709796247938, 'reg_alpha': 3.40701675640896, 'reg_lambda': 0.3512914021669605}. Best is trial 31 with value: 530989.4579723611.
[I 2026-06-01 14:04:08,678] Trial 35 finished with value: 531603.5759697323 and parameters: {'n_estimators': 771, 'learning_rate': 0.01899792533734254, 'num_leaves': 23, 'max_depth': 3, 'min_child_samples': 25, 'subsample': 0.5302758040614276, 'colsample_bytree': 0.7604232660961705, 'reg_alpha': 0.43073433972534036, 'reg_lambda': 1.828566196701798}. Best is trial 31 with value: 530989.4579723611.
[I 2026-06-01 14:04:08,752] Trial 36 finished with value: 543530.5052841526 and parameters: {'n_estimators': 852, 'learning_rate': 0.0193229783585594, 'num_leaves': 29, 'max_depth': 4, 'min_child_samples': 24, 'subsample': 0.6338388843562742, 'colsample_bytree': 0.650784155052736, 'reg_alpha': 0.055972022978073556, 'reg_lambda': 2.096863886089718}. Best is trial 31 with value: 530989.4579723611.
[I 2026-06-01 14:04:08,818] Trial 37 finished with value: 548048.1600489685 and parameters: {'n_estimators': 781, 'learning_rate': 0.03531584518398732, 'num_leaves': 21, 'max_depth': 9, 'min_child_samples': 32, 'subsample': 0.6863380599174833, 'colsample_bytree': 0.7575014584048835, 'reg_alpha': 0.014516821638914195, 'reg_lambda': 4.8207414627060405}. Best is trial 31 with value: 530989.4579723611.
[I 2026-06-01 14:04:08,857] Trial 38 finished with value: 559463.5369732209 and parameters: {'n_estimators': 949, 'learning_rate': 0.08578376557129355, 'num_leaves': 22, 'max_depth': 5, 'min_child_samples': 38, 'subsample': 0.5721710021385991, 'colsample_bytree': 0.7042341404596383, 'reg_alpha': 1.8201197935184836, 'reg_lambda': 1.2855214916496247}. Best is trial 31 with value: 530989.4579723611.
[I 2026-06-01 14:04:08,936] Trial 39 finished with value: 554452.9406203476 and parameters: {'n_estimators': 538, 'learning_rate': 0.011565952647420127, 'num_leaves': 24, 'max_depth': 3, 'min_child_samples': 42, 'subsample': 0.783638031340874, 'colsample_bytree': 0.7952782658390662, 'reg_alpha': 0.40432936273085424, 'reg_lambda': 0.43378722969929523}. Best is trial 31 with value: 530989.4579723611.
[I 2026-06-01 14:04:09,013] Trial 40 finished with value: 543711.9813452064 and parameters: {'n_estimators': 217, 'learning_rate': 0.014339570414885759, 'num_leaves': 95, 'max_depth': 4, 'min_child_samples': 22, 'subsample': 0.5149879800507505, 'colsample_bytree': 0.5384425525646477, 'reg_alpha': 0.0728972441146677, 'reg_lambda': 1.304852935581124}. Best is trial 31 with value: 530989.4579723611.
[I 2026-06-01 14:04:09,072] Trial 41 finished with value: 530171.2804197294 and parameters: {'n_estimators': 771, 'learning_rate': 0.02422135445288297, 'num_leaves': 33, 'max_depth': 3, 'min_child_samples': 30, 'subsample': 0.5286397552581956, 'colsample_bytree': 0.8245473454451236, 'reg_alpha': 1.0517792038162677, 'reg_lambda': 0.0014366804307858003}. Best is trial 41 with value: 530171.2804197294.
[I 2026-06-01 14:04:09,120] Trial 42 finished with value: 530392.4025044653 and parameters: {'n_estimators': 886, 'learning_rate': 0.04973363226444172, 'num_leaves': 36, 'max_depth': 3, 'min_child_samples': 32, 'subsample': 0.8998107743920858, 'colsample_bytree': 0.8345756671523877, 'reg_alpha': 1.023869089543687, 'reg_lambda': 0.0013712868889253422}. Best is trial 41 with value: 530171.2804197294.
[I 2026-06-01 14:04:09,156] Trial 43 finished with value: 530051.0791976411 and parameters: {'n_estimators': 895, 'learning_rate': 0.25644691368582195, 'num_leaves': 32, 'max_depth': 3, 'min_child_samples': 35, 'subsample': 0.8588860887796926, 'colsample_bytree': 0.8351733377025525, 'reg_alpha': 1.1278289093616878, 'reg_lambda': 0.0006872050547489114}. Best is trial 43 with value: 530051.0791976411.
[I 2026-06-01 14:04:09,190] Trial 44 finished with value: 533008.5417574341 and parameters: {'n_estimators': 881, 'learning_rate': 0.2724798172405922, 'num_leaves': 28, 'max_depth': 3, 'min_child_samples': 35, 'subsample': 0.8917478267363492, 'colsample_bytree': 0.847994025449279, 'reg_alpha': 2.8171669874725223, 'reg_lambda': 0.0005613587524928026}. Best is trial 43 with value: 530051.0791976411.
[I 2026-06-01 14:04:09,228] Trial 45 finished with value: 530175.9011860094 and parameters: {'n_estimators': 906, 'learning_rate': 0.13121471281142486, 'num_leaves': 45, 'max_depth': 3, 'min_child_samples': 32, 'subsample': 0.8593159489024348, 'colsample_bytree': 0.8823172269896216, 'reg_alpha': 1.118069910379134, 'reg_lambda': 0.0013141975326061862}. Best is trial 43 with value: 530051.0791976411.
[I 2026-06-01 14:04:09,269] Trial 46 finished with value: 530877.9603960939 and parameters: {'n_estimators': 923, 'learning_rate': 0.16016551465718765, 'num_leaves': 49, 'max_depth': 4, 'min_child_samples': 32, 'subsample': 0.8783285730987391, 'colsample_bytree': 0.8916052903767764, 'reg_alpha': 1.1165068832906069, 'reg_lambda': 0.002417023386075725}. Best is trial 43 with value: 530051.0791976411.
[I 2026-06-01 14:04:09,309] Trial 47 finished with value: 530899.0387425505 and parameters: {'n_estimators': 913, 'learning_rate': 0.1695255047481589, 'num_leaves': 49, 'max_depth': 4, 'min_child_samples': 34, 'subsample': 0.8771099638198272, 'colsample_bytree': 0.9049050532526854, 'reg_alpha': 7.019899183311734, 'reg_lambda': 0.0018879796242913956}. Best is trial 43 with value: 530051.0791976411.
[I 2026-06-01 14:04:09,345] Trial 48 finished with value: 543533.6338233574 and parameters: {'n_estimators': 994, 'learning_rate': 0.2665028988188917, 'num_leaves': 48, 'max_depth': 5, 'min_child_samples': 41, 'subsample': 0.9101973680829034, 'colsample_bytree': 0.928042880320735, 'reg_alpha': 0.9917457255497356, 'reg_lambda': 0.0018206373602156316}. Best is trial 43 with value: 530051.0791976411.

In [14]:
print(f"Best CV MSE  : {best_mse:.2f}")
print(f"Best CV RMSE : {best_rmse:.2f}")
print(f"Best params  : {best_params}")

Best CV MSE  : 514771.31
Best CV RMSE : 717.48
Best params  : {'n_estimators': 701, 'learning_rate': 0.23796774757282269, 'num_leaves': 59, 'max_depth': 3, 'min_child_samples': 27, 'subsample': 0.8224198027488112, 'colsample_bytree': 0.8529719414772412, 'reg_alpha': 4.722619165820532, 'reg_lambda': 0.00010300875864259597}

In [16]:
model = fit_final_lgbm(df_test_X, y, best_params)

In [18]:
importance = pd.Series(
    model.feature_importances_, index=get_lgb_features_cols()
).sort_values(ascending=False)
print("\nFeature importances (gain):")
print(importance.head(10).round(2))

Feature importances (gain):
temp_x_wind        332
sin_doy_3          281
hum                270
temp_atemp_diff    218
temp_x_hum         205
sin_doy_2          204
wind               192
cos_doy_2          172
cos_doy_3          168
temp               138
dtype: int32

# Save Submission

In [24]:
from scripts.save_submission import save_submission_csv

In [25]:
preds = model.predict(df_test_X)

df_submission = pd.DataFrame({"date": df_test_raw["date"], "pred": preds})

df_submission

          date         pred
1   2023-01-01  1072.637784
2   2023-01-02   826.803604
3   2023-01-03  1350.060570
4   2023-01-04  1542.820781
5   2023-01-05  1599.821451
..         ...          ...
361 2023-12-27  1207.326123
362 2023-12-28  2265.547368
363 2023-12-29  2437.864664
364 2023-12-30  2952.667331
365 2023-12-31  2451.866341

[365 rows x 2 columns]

In [26]:
save_submission_csv(df_submission)