In [6]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import pickle

In [7]:
df_res_a = pd.read_csv(f"params-random-forest/random_forest_4.csv", index_col=[0])

In [8]:
df_res_a.sort_values("val_rmse_mean").iloc[:10]

,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,train_rmse_mean,train_rmse_std,val_rmse_mean,val_rmse_std
8,21,sqrt,1,4,252,204.051274,5.305541,531.217226,58.923892
20,23,sqrt,1,4,252,204.112400,5.258694,531.238881,58.411356
32,25,sqrt,1,4,252,204.113068,5.251790,531.307948,58.427435
11,21,sqrt,1,4,255,204.012879,5.305325,531.325213,59.176505
26,24,sqrt,1,4,252,204.143858,5.268294,531.336219,58.478531
6,21,sqrt,1,4,250,204.179110,5.367482,531.341952,59.130499
23,23,sqrt,1,4,255,204.072905,5.258435,531.348967,58.667731
7,21,sqrt,1,4,251,204.216112,5.256607,531.356184,59.048518
18,23,sqrt,1,4,250,204.242274,5.320877,531.363648,58.616570
14,22,sqrt,1,4,252,204.126170,5.203004,531.369486,58.490807

In [9]:
df_res_b = pd.read_csv(f"params-random-forest/random_forest_5.csv", index_col=[0])

In [10]:
df_res_b.sort_values("val_rmse_mean").iloc[:10]

,max_depth,max_features,min_samples_leaf,min_samples_split,n_estimators,train_rmse_mean,train_rmse_std,val_rmse_mean,val_rmse_std
9,21,sqrt,1,4,252,204.051274,5.305541,531.217226,58.923892
23,23,sqrt,1,4,252,204.112400,5.258694,531.238881,58.411356
37,25,sqrt,1,4,252,204.113068,5.251790,531.307948,58.427435
30,24,sqrt,1,4,252,204.143858,5.268294,531.336219,58.478531
16,22,sqrt,1,4,252,204.126170,5.203004,531.369486,58.490807
2,20,sqrt,1,4,252,204.225191,5.296154,531.631971,58.593838
6,20,sqrt,1,8,252,267.679493,7.839940,537.356973,56.386791
13,21,sqrt,1,8,252,267.626651,7.858377,537.584777,56.414937
27,23,sqrt,1,8,252,267.667412,7.833615,537.610743,56.416684
41,25,sqrt,1,8,252,267.667412,7.833615,537.610743,56.416684